### PR TITLE
Pin specific version of sphinx to fix the doc builds

### LINKED ISSUE #395: PyNWB Docs not building on ReadTheDocx
## 1) Bug

The PyNWB docs are currently not building on ReadTheDocs. The culprit for the failing build seems to be that the PyNWB docs are being built with Sphinx 1.7.1. The other docs for NWB (e.g, the schema docs) seem to use Sphinx 1.6.5 instead and are still building. There is a current RTD GitHub issue for this here:

https://github.com/rtfd/readthedocs.org/issues/3769

I would say, lets just downgrade to Sphinx 1.6.5 for now.

### Steps to Reproduce

See, e.g., https://readthedocs.org/projects/pynwb/builds/6898276/

Here is what ReadTheDocs is trying to run:

```
 python /home/docs/checkouts/readthedocs.org/user_builds/pynwb/envs/latest/bin/sphinx-build -T -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html


Running Sphinx v1.7.1
loading translations [en]... done
making output directory...
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.h5py.org/en/latest/objects.inv...
loading intersphinx inventory from https://docs.python.org/3.5/objects.inv...
loading intersphinx inventory from http://matplotlib.org/objects.inv...
intersphinx inventory has moved: http://matplotlib.org/objects.inv -> https://matplotlib.org/objects.inv
loading intersphinx inventory from http://docs.scipy.org/doc/scipy/reference/objects.inv...
intersphinx inventory has moved: http://docs.scipy.org/doc/scipy/reference/objects.inv -> https://docs.scipy.org/doc/scipy/reference/objects.inv
loading intersphinx inventory from http://docs.scipy.org/doc/numpy/objects.inv...
intersphinx inventory has moved: http://docs.scipy.org/doc/numpy/objects.inv -> https://docs.scipy.org/doc/numpy/objects.inv
/home/docs/checkouts/readthedocs.org/user_builds/pynwb/envs/latest/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
usage: usage: sphinx-build [OPTIONS] -o <OUTPUT_PATH> <MODULE_PATH> [EXCLUDE_PATTERN, ...]
sphinx-build: error: argument -d/--maxdepth: invalid int value: '_build/doctrees-readthedocs'
Command time: 10s Return: 2

```

The part that's a bit strange here is that ```-d/--maxdepth``` are parameters of ```sphinx-apidoc``` not ```sphinx-build```.  ```sphinx-build``` also has a ```-d``` option, but it expects a path, which looks correct in the call.

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you included a minimal code snippet that reproduces the issue you are encountering?

### PR DESCRIPTION
**Pull request by dorukozturk**
Fixes #395

### CODE REVIEW

**Review by oruebel — APPROVED** [review]

**Comment by oruebel** [comment]
@dorukozturk thanks for the fix! Just for my own understanding, where is requirements-doc.txt set in the ReadTheDocs interface, I just could not find it in the settings of the ReadTheDocs site.

**Comment by oruebel** [comment]
@dorukozturk I just triggered a rebuild of the docs on ReadTheDocs after I merged this pull request and it looks like ReadTheDocs it is still using Sphinx 1.7.1.

**Comment by jcfr** [comment]
Good point.

I just updated the advanced settings of readthedocs to use the requirement files:

image

**Comment by oruebel** [comment]
Thanks for the quick fix! Looks like the docs are building now.

**Pull request merged**
