### PR TITLE
Enh/experimenters

### LINKED ISSUE #985: Multiple experimenters request
Feature request: 

Right now the "experimenter" field is a single string. It would be useful to have a standard for multiple experimenters, either a list of names separated by some delimiter or perhaps an array of strings.

### PR DESCRIPTION
**Pull request by ajtritt**
## Motivation

fix #985

## Checklist

- [X] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured the PR description clearly describes problem and the solution?
- [X] Is your contribution compliant with our coding style ? This can be checked running `flake8` from the source directory.
- [X] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [X] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ?

### CODE REVIEW

**Comment by bendichter** [comment]
I'm worried this will break read in matnwb

**Comment by t-b** [comment]
I would say this is schema breaking as well.

**Comment by oruebel** [comment]
@ln-vidrio @nclack is this change Ok for MatNWB?

**Comment by lawrence-mbf** [comment]
Testing just the schema change seemed to work okay if the stored dataset is an array.  This will require regenerating from the schema though.

**Comment by bendichter** [comment]
OK, regenerating from schema is not a big deal. I say we move forward with this

**Review by bendichter — APPROVED** [review]

**Pull request merged**
