### PR TITLE
Change manifold to pixel_origin and pixel_deltas

### PR DESCRIPTION
**Pull request by bendichter**
## Motivation

The `manifold` datatype of `ImagingPlane` is confusing and inefficient. It is being replaced with `pixel_origin` and `pixel_deltas` which specify where the pixels of the image are in space. This assumes a grid layout of the pixels. Non-grids will require an extension.

addresses #554

## How to test the behavior?
```python
from pynwb.ophys import OpticalChannel, ImagingPlane
oc = OpticalChannel('test_name', 'test_source', 'description', 500.)
ImagingPlane('test_imaging_plane', 'test source', oc, 'description', 'device', 600.,
                          'imaging_rate', 'indicator', 'location', (.1, .2), (.0, .0), 'reference_frame')
```

## Checklist

- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR description clearly describes problem and the solution?
- [x] Is your contribution compliant with our coding style ? This can be checked running `flake8` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [x] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ?

### CODE REVIEW

**Comment by bendichter** [comment]
I'm not sure how to fix the last failing test:

```python
======================================================================
FAIL: test_write_cache_spec (test_io.TestHDF5Writer) (neurodata_type='ImagingPlane', test='cached spec preserved original spec')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bendichter/dev/pynwb/tests/integration/test_io.py", line 119, in test_write_cache_spec
    self.assertDictEqual(original_spec, cached_spec)
AssertionError: {'att[16 chars]pe': 'text', 'doc': "Value is 'Metadata about [2313 chars]ces'} != {'att[16 chars]pe': u'text', 'doc': u"Value is 'Metadata abou[2366 chars]ces'}
Diff is 8705 characters long. Set self.maxDiff to None to see it.
```

**Comment by ajtritt** [comment]
@bendichter just to confirm, this is just a different way of representing the same data, correct?

**Comment by bendichter** [comment]
well, not exactly. The previous way would allow you to have irregular sampling. This enforces that you must have uniform grids. The irregular sampling will be useful for random sampling techniques, but from what I understand they'll need an extension anyway. The majority of labs use a uniform grid, so this is a much more straightforward and compact way of representing space.

**Comment by bendichter** [comment]
To me this seems analogous to `TimeSeries.timestamps`. In that case we provided two options: specify start and delta for constant sampling, or specify all timestamps for non-uniform sampling. Here we could do the same thing, where we allow the user to specify the start and deltas in physical space for cases where each dimension has a constant spatial sampling (this is true most of the time), and we can continue to support the old way, which would work for the rare cases of irregular spatial sampling. This change would allow for a much more compact and intuitive representation of space for most labs.

**Comment by rly** [comment]
I agree with Ben's last comment here -- allow both methods to work, especially now that we do not want to break backwards compatibility with 2.0.

**Comment by rly** [comment]
Using `pixel_origin` and `pixel_deltas` would still require a unit for the `pixel_deltas` values. To make pixel spacing like timestamps, I would create a group called `uniform_sampling` with datasets `pixel_origin` and `pixel_deltas` and an attribute `unit`). 

This is different from timestamps (below) where, to be consistent, I would have created a group called `uniform_sampling` with attributes `starting_time`, `rate`, and `unit`, but it might be too late for that.

For reference, the schema for `TimeSeries` says:
```yaml
  - name: starting_time
    dtype: float64
    doc: 'The timestamp of the first sample. COMMENT: When timestamps are uniformly
      spaced, the timestamp of the first sample can be specified and all subsequent
      ones calculated from the sampling rate.'
    attributes:
    - name: rate
      dtype: float32
      doc: 'Sampling rate, in Hz COMMENT: Rate information is stored in Hz'
    - name: unit
      dtype: text
      doc: Value is 'Seconds'
      value: Seconds
    quantity: '?'
  - name: timestamps
    dtype: float64
    doc: 'Timestamps for samples stored in data.COMMENT: Timestamps here have all
      been corrected to the common experiment master-clock. Time is stored as seconds
      and all timestamps are relative to experiment start time.'
    attributes:
    - name: interval
      dtype: int32
      doc: Value is '1'
      value: 1
    - name: unit
      dtype: text
      doc: Value is 'Seconds'
      value: Seconds
    dims:
    - num_times
    quantity: '?'
    shape:
    - null
```

**Comment by bendichter** [comment]
I agree about the need for a unit. Let's discuss the options for how to include this information. Making a group seems like it may be more complicated than necessary

**Comment by ajtritt** [comment]
@bendichter @rly What's the status of this? Tomorrow marks this PR's first birthday, and there hasn't been activity for six weeks. 

From my end, this seems reasonable and something that should be included.

@bendichter do you want this to automatically close #554? If so, "addresses" needs to be changed to something from [this list](https://help.github.com/en/articles/closing-issues-using-keywords)

**Comment by bendichter** [comment]
The status is this racked up merge conflicts but it is still definitely something I want to push through

**Comment by bendichter** [comment]
I use "addresses" when it's a partial fix and shouldn't close the issue

**Comment by rly** [comment]
I will resolve the conflicts, set units to be fixed to meters, and make `manifold` optional and deprecated. How does this sound?

**Comment by oruebel** [comment]
> How does this sound?

Sounds good

**Comment by bendichter** [comment]
Yeah, sounds good

**Pull request closed without merging**
