### PR TITLE
Remove RegionReferences from VectorIndex and make ROITable a DynamicTable

### LINKED ISSUE #662: Can't write to an existing file
## 1) Bug

pynwb throws an error when you append to an existing file that contains an electrode_group

### Steps to Reproduce
```python
from datetime import datetime
import numpy as np
from pynwb import NWBFile, NWBHDF5IO, TimeSeries
from pynwb.ecephys import ElectricalSeries, LFP

FILENAME = 'test_append.nwb'

if __name__ == '__main__':
    nwb = NWBFile(source='', session_description='', identifier='', session_start_time=datetime.now())
    proc_mod = nwb.create_processing_module(name='test_proc_mod', source='', description='')
    proc_inter = LFP(source='', name='test_proc_dset')
    proc_mod.add_data_interface(proc_inter)
    device = nwb.create_device(name='test_device', source='')
    e_group = nwb.create_electrode_group(
        name='test_electrode_group',
        source='',
        description='',
        location='',
        device=device
    )

    with NWBHDF5IO(FILENAME, mode='w') as io:
        io.write(nwb)

    with NWBHDF5IO(FILENAME, mode='a') as io:
        nwb = io.read()
        ts2 = TimeSeries(name='timeseries2', source='source2', data=[4,5,6],
                unit='na1', rate=1.0, starting_time=0.0)
        nwb.add_acquisition(ts2)
        io.write(nwb)
```
The error is:
```
Traceback (most recent call last):
  File "scripts/test_nwb_append.py", line 58, in <module>
    io.write(nwb)
  File "/home/vyassa/anaconda2/envs/mars/lib/python3.5/site-packages/pynwb/form/utils.py", line 337, in func_call
    return func(self, **parsed['args'])
  File "/home/vyassa/anaconda2/envs/mars/lib/python3.5/site-packages/pynwb/form/backends/hdf5/h5tools.py", line 186, in write
    call_docval_func(super(HDF5IO, self).write, kwargs)
  File "/home/vyassa/anaconda2/envs/mars/lib/python3.5/site-packages/pynwb/form/utils.py", line 235, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/home/vyassa/anaconda2/envs/mars/lib/python3.5/site-packages/pynwb/form/utils.py", line 337, in func_call
    return func(self, **parsed['args'])
  File "/home/vyassa/anaconda2/envs/mars/lib/python3.5/site-packages/pynwb/form/backends/io.py", line 40, in write
    self.write_builder(f_builder, **kwargs)
  File "/home/vyassa/anaconda2/envs/mars/lib/python3.5/site-packages/pynwb/form/utils.py", line 337, in func_call
    return func(self, **parsed['args'])
  File "/home/vyassa/anaconda2/envs/mars/lib/python3.5/site-packages/pynwb/form/backends/hdf5/h5tools.py", line 367, in write_builder
    self.write_group(self.__file, gbldr)
  File "/home/vyassa/anaconda2/envs/mars/lib/python3.5/site-packages/pynwb/form/utils.py", line 337, in func_call
    return func(self, **parsed['args'])
  File "/home/vyassa/anaconda2/envs/mars/lib/python3.5/site-packages/pynwb/form/backends/hdf5/h5tools.py", line 504, in write_group
    self.write_group(group, sub_builder)
  File "/home/vyassa/anaconda2/envs/mars/lib/python3.5/site-packages/pynwb/form/utils.py", line 337, in func_call
    return func(self, **parsed['args'])
  File "/home/vyassa/anaconda2/envs/mars/lib/python3.5/site-packages/pynwb/form/backends/hdf5/h5tools.py", line 504, in write_group
    self.write_group(group, sub_builder)
  File "/home/vyassa/anaconda2/envs/mars/lib/python3.5/site-packages/pynwb/form/utils.py", line 337, in func_call
    return func(self, **parsed['args'])
  File "/home/vyassa/anaconda2/envs/mars/lib/python3.5/site-packages/pynwb/form/backends/hdf5/h5tools.py", line 514, in write_group
    self.write_link(group, sub_builder)
  File "/home/vyassa/anaconda2/envs/mars/lib/python3.5/site-packages/pynwb/form/utils.py", line 337, in func_call
    return func(self, **parsed['args'])
  File "/home/vyassa/anaconda2/envs/mars/lib/python3.5/site-packages/pynwb/form/backends/hdf5/h5tools.py", line 548, in write_link
    parent[name] = link_obj
  File "/home/vyassa/anaconda2/envs/mars/lib/python3.5/site-packages/h5py/_hl/group.py", line 291, in __setitem__
    lcpl=lcpl, lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5l.pyx", line 145, in h5py.h5l.LinkProxy.create_soft
RuntimeError: Unable to create link (name already exists)
```
### Environment
- **Python Executable:** Conda
- **Python Version:** Python 3.5.1
- **Operating System:** Linux (Ubuntu 18.04)
- **Pynwb Version:** pynwb 0.5.1

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?

### LINKED ISSUE #663: Make ROITable a DynamicTable
### Problem/Use Case
ROITable is currently a compound-dtype table. This makes it hard to extend and inefficient for querying along a single feature. Additionally, it forces us to require pixel_mask *and* image_mask. Making ROITable a DynamicTable makes the code for requiring one or the other much simpler.

Additionally, pixel_mask will be replaced by the updated VectorIndex, which does not use RegionReferences for indexing a VectorData. Removing this will make the schema less dependent on HDF5 primitives and make it easier to use alternative backends.

Relates to #643 

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you included a minimal code snippet that reproduces the issue you are encountering?

### PR DESCRIPTION
**Pull request by ajtritt**
## Motivation
Fix #663 

- `pixel_mask` or `image_mask` required, but not both. both can be supplied
- use integer id rather than ROI name
- additional metadata can be added to using `PlaneSegmentation.add_column` or `PlaneSegmentation.add_vector_data`

## How to test the behavior?
```python
w, h = 5, 5
img_mask = [[[1.0 for x in range(w)] for y in range(h)], [[2.0 for x in range(w)] for y in range(h)]]
pix_mask = [(1, 2, 1.0), (3, 4, 1.0), (5, 6, 1.0),
            (7, 8, 2.0), (9, 10, 2.)]
imaging_plane = ...
image_series = ...
pS = PlaneSegmentation('integration test PlaneSegmentation', 'plane segmentation description',
                       imaging_plane, 'test_plane_seg_name', image_series)
pS.add_roi(pixel_mask=pix_mask[0:3], image_mask=img_mask[0])
pS.add_roi(pixel_mask=pix_mask[3:5], image_mask=img_mask[1])

# retrieve data

pS['image_mask'][0]
pS['pixel_mask'][0]
pS['image_mask'][1]
pS['pixel_mask'][1]
```

Also fix #662 

## Checklist

- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR description clearly describes problem and the solution?
- [x] Is your contribution compliant with our coding style ? This can be checked running `flake8` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [x] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ?

### CODE REVIEW

**Comment by ajtritt** [comment]
@nicain I would especially appreciate your feedback on the [Brain Observatory example](https://github.com/NeurodataWithoutBorders/pynwb/pull/665/files#diff-04c8e6c4fa33c473d4f78a8bfa6d620e)

**Comment by t-b** [comment]
@ajtritt With my self-proclaimed-HDF5-feature-checker-guy helm on: How does the DynamicTable relate to a HDF5 file? Does that use any new fancy HDF5 features? Is there a file I can just create and look at it?

**Comment by ajtritt** [comment]
@t-b DynamicTable is just a group of datasets, that have the same length on the first dimension (at this point, that’s only enforced by the API, and nothing in the schema can specify this). It also has a required dataset that stores row identifiers. 

If you run the ecephys or ophys examples (under docs/gallery/domain), you can make files that have a DynamicTable.  

The fanciest HDF5 feature that gets used is a reference stored as an attribute—VectorIndex stores a reference to the VectorData object it indexes.

**Comment by t-b** [comment]
@ajtritt Okay so Igor has some issues with reference to groups. But these look like I can get them fixed. Matlab is fine with that according to the documentation.

**Comment by bendichter** [comment]
It would be nice to convert between `image_mask` and `pixel_mask`, but that's not critical right now. Did you include tests for only supplying `image_mask` or `pixel_mask` and not both?

**Review by oruebel — DISMISSED** [review]

**Comment by oruebel** [comment]
@nicain did you have a chance to look at this?

**Comment by ajtritt** [comment]
@bendichter 

> Did you include tests for only supplying image_mask or pixel_mask and not both?

Thanks for checking. I just added them

**Review by bendichter — APPROVED** [review]

**Pull request merged**
