### PR TITLE
Doc fixes

### LINKED ISSUE #488: sphinx not linking internally
## 1) Bug

Sphinx is not building links to types defined within PyNWB, but it can link to other types found outside of PyNWB. 

For example, on the TimeSeries API doc, the allowable types for the *data* argument don't provide links to anything defined within NWB e.g. AbstractDataChunkIterator, but it links to the h5py API docs for Dataset. 
http://pynwb.readthedocs.io/en/latest/pynwb.base.html#pynwb.base.TimeSeries

## Checklist

- [ ] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [ ] Have you included a brief and descriptive title?
- [ ] Have you included a clear description of the problem you are trying to solve?
- [ ] Have you included a minimal code snippet that reproduces the issue you are encountering?

### PR DESCRIPTION
**Pull request by t-b**
Together with a HDMF fix the documentation now looks like

grafik

Close #488.

### CODE REVIEW

**Comment by oruebel** [comment]
Very nice 👍

**Comment by t-b** [comment]
Requires https://github.com/hdmf-dev/hdmf/pull/61 to be merged as well.

**Review by oruebel — DISMISSED** [review]

**Comment by t-b** [comment]
@oruebel @ajtritt @bendichter Any objections merging that? The test failures are not related to this PR.

**Review by bendichter — APPROVED** [review]
looks great!

**Review by oruebel — APPROVED** [review]

**Comment by t-b** [comment]
@bendichter Could you merge as well? I'm not powerful enough to do that.

**Pull request merged**
