### PR TITLE
Fix `channel_conversion` use in `TimeSeries.get_data_in_units`

### PR DESCRIPTION
**Pull request by rohanshah**
## Motivation

Fixes issue discussed here: https://github.com/NeurodataWithoutBorders/helpdesk/discussions/83

## How to test the behavior?
Updated unit test to reflect functional change

## Checklist

- [x] Did you update CHANGELOG.md with your changes?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR clearly describes the problem and the solution?
- [x] Is your contribution compliant with our coding style? This can be checked running `flake8` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [x] Have you included the relevant issue number using "Fix #XXX" notation where XXX is the issue number? By including "Fix #XXX" you allow GitHub to close issue #XXX when the PR is merged.

### CODE REVIEW

**Review by bendichter — APPROVED** [review]
LGTM!

**Comment by rohanshah** [comment]
thanks @bendichter ! no rush on my end but what's the best way to have this merged and into the next release?

**Comment by bendichter** [comment]
@rohanshah I'm running tests now. If/when those pass, it'll automatically be merged to dev and will be incorporated in the next release

**Comment by rly** [comment]
Thanks for the bug fix @rohanshah !

**Pull request merged**
