### PR TITLE
Release 2.3.0

### PR DESCRIPTION
**Pull request by mavaylon1**
Prepare for release of PyNWB [version]

### Before merging:
- [x] Major and minor releases: Update package versions in `requirements.txt`, `requirements-dev.txt`,
  `requirements-doc.txt`, `requirements-min.txt`, `setup.py` as needed
  See https://requires.io/github/NeurodataWithoutBorders/pynwb/requirements/?branch=dev
- [x] Check legal file dates and information in `Legal.txt`, `license.txt`, `README.rst`, `docs/source/conf.py`,
  and any other locations as needed
- [x] Update `setup.py` as needed
- [x] Update `README.rst` as needed
- [x] Update `src/pynwb/nwb-schema` submodule as needed. Check the version number and commit SHA manually
- [x] Update changelog (set release date) in `CHANGELOG.md` and any other docs as needed
- [x] Run tests locally including gallery, validation, and streaming tests, and inspect all warnings and outputs
  (`python test.py -v -p -i -b -w -r > out.txt 2>&1`)
- [x] Test docs locally (`make clean`, `make html`)
- [x] Push changes to this PR and make sure all PRs to be included in this release have been merged
- [x] Check that the readthedocs build for this PR succeeds (build latest to pull the new branch, then activate and
  build docs for new branch): https://readthedocs.org/projects/pynwb/builds/

### After merging:
1. Create release by following steps in `docs/source/make_a_release.rst` or use alias `git pypi-release [tag]` if set up
2. After the CI bot creates the new release (wait ~10 min), update the release notes on the
   [GitHub releases page](https://github.com/NeurodataWithoutBorders/pynwb/releases) with the changelog
3. Check that the readthedocs "latest" and "stable" builds run and succeed
4. Update [conda-forge/pynwb-feedstock](https://github.com/conda-forge/pynwb-feedstock) with the latest version number
   and SHA256 retrieved from PyPI > PyNWB > Download Files > View hashes for the `.tar.gz` file. Re-render as needed

### CODE REVIEW

**Comment by mavaylon1** [comment]
@rly not sure why this happens after running 
```
make clean
make html
```
I'll investigate. 
```
Traceback (most recent call last):
  File "/Users/mavaylon/opt/anaconda3/envs/hdmf_clone/lib/python3.9/site-packages/sphinx/config.py", line 340, in eval_config_file
    exec(code, namespace)
  File "/Users/mavaylon/Research/NWB/pynwb/docs/source/conf.py", line 36, in <module>
    from pynwb._version import get_versions
  File "/Users/mavaylon/Research/NWB/pynwb/src/pynwb/__init__.py", line 335, in <module>
    from . import io as __io  # noqa: F401,E402
  File "/Users/mavaylon/Research/NWB/pynwb/src/pynwb/io/__init__.py", line 1, in <module>
    from . import base as __base
  File "/Users/mavaylon/Research/NWB/pynwb/src/pynwb/io/base.py", line 3, in <module>
    from .core import NWBContainerMapper
  File "/Users/mavaylon/Research/NWB/pynwb/src/pynwb/io/core.py", line 9, in <module>
    from pynwb.file import NWBFile
  File "/Users/mavaylon/Research/NWB/pynwb/src/pynwb/file.py", line 22, in <module>
    from .ophys import ImagingPlane
  File "/Users/mavaylon/Research/NWB/pynwb/src/pynwb/ophys.py", line 124, in <module>
    class OnePhotonSeries(ImageSeries):
  File "/Users/mavaylon/Research/NWB/pynwb/src/pynwb/__init__.py", line 135, in _dec
    __TYPE_MAP.register_container_type(namespace, neurodata_type, cls)
  File "/Users/mavaylon/Research/NWB/hdmf2/hdmf/src/hdmf/utils.py", line 645, in func_call
    return func(args[0], **pargs)
  File "/Users/mavaylon/Research/NWB/hdmf2/hdmf/src/hdmf/build/manager.py", line 724, in register_container_type
    spec = self.__ns_catalog.get_spec(namespace, data_type)  # make sure the spec exists
  File "/Users/mavaylon/Research/NWB/hdmf2/hdmf/src/hdmf/utils.py", line 645, in func_call
    return func(args[0], **pargs)
  File "/Users/mavaylon/Research/NWB/hdmf2/hdmf/src/hdmf/spec/namespace.py", line 316, in get_spec
    return self.__namespaces[namespace].get_spec(data_type)
  File "/Users/mavaylon/Research/NWB/hdmf2/hdmf/src/hdmf/utils.py", line 645, in func_call
    return func(args[0], **pargs)
  File "/Users/mavaylon/Research/NWB/hdmf2/hdmf/src/hdmf/spec/namespace.py", line 150, in get_spec
    raise ValueError("No specification for '%s' in namespace '%s'" % (data_type, self.name))
ValueError: No specification for 'OnePhotonSeries' in namespace 'core'

```

**Comment by rly** [comment]
Did you update your local nwb-schema submodule?

**Comment by mavaylon1** [comment]
I think there was some conflicts on my end, but it was resolved by creating a new conda env and reinstalling.

**Review by rly — APPROVED** [review]

**Comment by rly** [comment]
Looks good. Thanks for going throuogh the checklist. I guess there are no changes here and they were all done as part of #1611. Please go ahead with the release.

**Pull request merged**
