### PR TITLE
Enh/spike restructure

### PR DESCRIPTION
**Pull request by ajtritt**
## Motivation

Restructure UnitTimes to store spike data more efficiently

See https://github.com/NeurodataWithoutBorders/nwb-schema/issues/117

## How to test the behavior?
```python
from pynwb.misc import UnitTimes
ut = UnitTimes('example use of UnitTimes')
ut.add_spike_times(0, [0, 1, 2])
ut.add_spike_times(1, [3, 4, 5])
assert ut.get_unit_spike_times(0) == [0, 1, 2]
assert ut.get_unit_spike_times(1)  == [3, 4, 5]
```

## Checklist

- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR description clearly describes problem and the solution?
- [x] Is your contribution compliant with our coding style ? This can be checked running `flake8` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [x] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ?

### CODE REVIEW

**Comment by bendichter** [comment]
I'll pull this now and test it out

**Comment by bendichter** [comment]
I think I found an issue involving referencing the data on a loaded file.

The following works:

```python
from pynwb.misc import UnitTimes
ut = UnitTimes('example use of UnitTimes')
ut.add_spike_times(0, [0, 1, 2])
ut.add_spike_times(1, [3, 4, 5])

ut.spike_times_index[0][:]
```
output: `[0, 1, 2]`

However, if you try to save and load an NWB file, it no longer works:

```python
from pynwb import load_namespaces, get_class, NWBHDF5IO, NWBFile
from datetime import datetime

nwbfile = NWBFile(source='source',
                  session_description='session_description',
                  identifier='identifier',
                  session_start_time=datetime.now(),
                  file_create_date=datetime.now(),
                  institution='institution',
                  lab='lab')

module = nwbfile.create_processing_module('test', source='source', description='description')
module.add_container(ut)

with NWBHDF5IO('test2.nwb','w') as io:
    io.write(nwbfile, cache_spec=False)

####

with NWBHDF5IO('test2.nwb', 'r') as io:
    xx = io.read()
    ut = xx.modules['test'].containers[0]
    print(ut.spike_times_index[0]) # this works
    print(ut.spike_times[:])  # this works
    print(ut.spike_times_index[0][:])  # this doesn't work
```

causes error:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-54-b9504efcbcb0> in <module>()
      2     xx = io.read()
      3     ut = xx.modules['test'].containers[0]
----> 4     print(ut.spike_times_index[0][:])

TypeError: 'h5py.h5r.RegionReference' object is not subscriptable
```

**Comment by bendichter** [comment]
I've had some other issues with round-trips to disk. Would it be possible to add more round trips to the testing framework?

**Comment by oruebel** [comment]
@bendichter when you encounter such errors it would be great if you could create test cases for the test suite that trigger the error so that we can make sure we don't hit that error again in the future. An additional benefit is that by tying bug reports to pull requests that add new test-cases that trigger the bug would also help us with debugging.

**Comment by bendichter** [comment]
@oruebel sure, I can help with that.
@ajtritt How would you feel about a context for this:

```python
import os
from datetime import datetime

from pynwb import NWBFile
from pynwb.misc import UnitTimes

class ContainerRoundTrip():
    
    def __init__(self, container, filename='temp.nwb'):
        self.container = container
        self.filename = filename
        
    def __enter__(self):
        nwbfile = NWBFile(source='source',
                  session_description='session_description',
                  identifier='identifier',
                  session_start_time=datetime.now(),
                  file_create_date=datetime.now(),
                  institution='institution',
                  lab='lab')
        module = nwbfile.create_processing_module('test', source='source', description='description')
        module.add_container(self.container)
        
        with NWBHDF5IO(self.filename, 'w') as io:
            io.write(nwbfile)
        self.io = NWBHDF5IO(self.filename, 'r')
        nwbfile = self.io.read()
        container = nwbfile.modules['test'].containers[0]
        return container

    def __exit__(self, type, value, traceback):
        self.io.close()
        os.remove(self.filename)

###

ut = UnitTimes('example use of UnitTimes')
ut.add_spike_times(0, [0, 1, 2])
ut.add_spike_times(1, [3, 4, 5])

with ContainerRoundTrip(ut) as ut:
    print(ut.spike_times_index[0]) # this works
    print(ut.spike_times[:])  # this works
    print(ut.spike_times_index[0][:])  # this doesn't work
```

**Comment by bendichter** [comment]
Nice! Could you also add some way to turn compression on?

**Comment by bendichter** [comment]
For me this works when I run isolated test cases, but there's a bug when I try to use this data structure within the nwbfile of a full dataset:

```python
ns_path = 'general.namespace.yaml'
load_namespaces(ns_path)

with NWBHDF5IO(fpath) as io:
    nwbfile = io.read()
```

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-49-b0a69b544f9c> in <module>()
      3 
      4 with NWBHDF5IO(fpath) as io:
----> 5     nwbfile = io.read()

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    346                     msg = ', '.join(parse_err)
    347                     raise_from(TypeError(msg), None)
--> 348                 return func(self, **parsed['args'])
    349         else:
    350             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/backends/io.py in read(self, **kwargs)
     30     @docval(returns='the Container object that was read in', rtype=Container)
     31     def read(self, **kwargs):
---> 32         f_builder = self.read_builder()
     33         container = self.__manager.construct(f_builder)
     34         return container

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    346                     msg = ', '.join(parse_err)
    347                     raise_from(TypeError(msg), None)
--> 348                 return func(self, **parsed['args'])
    349         else:
    350             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py in read_builder(self)
    149         f_builder = self.__read.get(self.__file)
    150         if f_builder is None:
--> 151             f_builder = self.__read_group(self.__file, ROOT_NAME)
    152             self.__read[self.__file] = f_builder
    153         return f_builder

~/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py in __read_group(self, h5obj, name)
    219                         obj_type = kwargs['groups']
    220                     if builder is None:
--> 221                         builder = read_method(sub_h5obj)
    222                         self.__set_built(sub_h5obj.file.filename, sub_h5obj.name, builder)
    223                     obj_type[builder.name] = builder

~/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py in __read_group(self, h5obj, name)
    219                         obj_type = kwargs['groups']
    220                     if builder is None:
--> 221                         builder = read_method(sub_h5obj)
    222                         self.__set_built(sub_h5obj.file.filename, sub_h5obj.name, builder)
    223                     obj_type[builder.name] = builder

~/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py in __read_group(self, h5obj, name)
    219                         obj_type = kwargs['groups']
    220                     if builder is None:
--> 221                         builder = read_method(sub_h5obj)
    222                         self.__set_built(sub_h5obj.file.filename, sub_h5obj.name, builder)
    223                     obj_type[builder.name] = builder

~/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py in __read_dataset(self, h5obj, name)
    261         elif ndims == 1 and h5obj.dtype == np.dtype('O'):    # read list of strings
    262             elem1 = h5obj[0]
--> 263             d = None
    264             if isinstance(elem1, text_type):
    265                 d = JITDataset(h5obj)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

~/anaconda3/lib/python3.6/site-packages/h5py-2.6.0-py3.6-macosx-10.7-x86_64.egg/h5py/_hl/dataset.py in __getitem__(self, args)
    460 
    461         # Perform the dataspace selection.
--> 462         selection = sel.select(self.shape, args, dsid=self.id)
    463 
    464         if selection.nselect == 0:

~/anaconda3/lib/python3.6/site-packages/h5py-2.6.0-py3.6-macosx-10.7-x86_64.egg/h5py/_hl/selections.py in select(shape, args, dsid)
     90 
     91     sel = SimpleSelection(shape)
---> 92     sel[args]
     93     return sel
     94 

~/anaconda3/lib/python3.6/site-packages/h5py-2.6.0-py3.6-macosx-10.7-x86_64.egg/h5py/_hl/selections.py in __getitem__(self, args)
    257             return self
    258 
--> 259         start, count, step, scalar = _handle_simple(self.shape,args)
    260 
    261         self._id.select_hyperslab(start, count, step)

~/anaconda3/lib/python3.6/site-packages/h5py-2.6.0-py3.6-macosx-10.7-x86_64.egg/h5py/_hl/selections.py in _handle_simple(shape, args)
    445         else:
    446             try:
--> 447                 x,y,z = _translate_int(int(arg), length)
    448                 s = True
    449             except TypeError:

~/anaconda3/lib/python3.6/site-packages/h5py-2.6.0-py3.6-macosx-10.7-x86_64.egg/h5py/_hl/selections.py in _translate_int(exp, length)
    465 
    466     if not 0<=exp<length:
--> 467         raise ValueError("Index (%s) out of range (0-%s)" % (exp, length-1))
    468 
    469     return exp, 1, 1

ValueError: Index (0) out of range (0--1)
```

I'm working on tracking down the root cause. If you have any ideas/hints I'd appreciate it.

**Comment by bendichter** [comment]
What should the behavior be if a user adds spikes to a unit_id that already exists? e.g.
```python
ut.add_spike_times(0, [0., 1., 2.])
ut.add_spike_times(0, [3., 4., 5.])
```

**Review by oruebel — DISMISSED** [review]

**Comment by bendichter** [comment]
I'm trying to use this structure in a full dataset and I'm running into an error. I'm working on isolating the issue and reproducing with minimal code, because the write script isn't really shareable right now. The error is on the file read:

```python
from pynwb import NWBHDF5IO, load_namespaces

ns_path = 'general.namespace.yaml'
load_namespaces(ns_path)

with NWBHDF5IO(fpath) as io:
    nwbfile = io.read()
```


error:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-b0a69b544f9c> in <module>()
      3 
      4 with NWBHDF5IO(fpath) as io:
----> 5     nwbfile = io.read()

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    346                     msg = ', '.join(parse_err)
    347                     raise_from(TypeError(msg), None)
--> 348                 return func(self, **parsed['args'])
    349         else:
    350             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/backends/io.py in read(self, **kwargs)
     30     @docval(returns='the Container object that was read in', rtype=Container)
     31     def read(self, **kwargs):
---> 32         f_builder = self.read_builder()
     33         container = self.__manager.construct(f_builder)
     34         return container

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    346                     msg = ', '.join(parse_err)
    347                     raise_from(TypeError(msg), None)
--> 348                 return func(self, **parsed['args'])
    349         else:
    350             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py in read_builder(self)
    149         f_builder = self.__read.get(self.__file)
    150         if f_builder is None:
--> 151             f_builder = self.__read_group(self.__file, ROOT_NAME)
    152             self.__read[self.__file] = f_builder
    153         return f_builder

~/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py in __read_group(self, h5obj, name)
    219                         obj_type = kwargs['groups']
    220                     if builder is None:
--> 221                         builder = read_method(sub_h5obj)
    222                         self.__set_built(sub_h5obj.file.filename, sub_h5obj.name, builder)
    223                     obj_type[builder.name] = builder

~/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py in __read_group(self, h5obj, name)
    219                         obj_type = kwargs['groups']
    220                     if builder is None:
--> 221                         builder = read_method(sub_h5obj)
    222                         self.__set_built(sub_h5obj.file.filename, sub_h5obj.name, builder)
    223                     obj_type[builder.name] = builder

~/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py in __read_group(self, h5obj, name)
    219                         obj_type = kwargs['groups']
    220                     if builder is None:
--> 221                         builder = read_method(sub_h5obj)
    222                         self.__set_built(sub_h5obj.file.filename, sub_h5obj.name, builder)
    223                     obj_type[builder.name] = builder

~/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py in __read_dataset(self, h5obj, name)
    260                 kwargs["data"] = scalar
    261         elif ndims == 1 and h5obj.dtype == np.dtype('O'):    # read list of strings
--> 262             elem1 = h5obj[0]
    263             d = None
    264             if isinstance(elem1, text_type):

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

~/anaconda3/lib/python3.6/site-packages/h5py-2.6.0-py3.6-macosx-10.7-x86_64.egg/h5py/_hl/dataset.py in __getitem__(self, args)
    460 
    461         # Perform the dataspace selection.
--> 462         selection = sel.select(self.shape, args, dsid=self.id)
    463 
    464         if selection.nselect == 0:

~/anaconda3/lib/python3.6/site-packages/h5py-2.6.0-py3.6-macosx-10.7-x86_64.egg/h5py/_hl/selections.py in select(shape, args, dsid)
     90 
     91     sel = SimpleSelection(shape)
---> 92     sel[args]
     93     return sel
     94 

~/anaconda3/lib/python3.6/site-packages/h5py-2.6.0-py3.6-macosx-10.7-x86_64.egg/h5py/_hl/selections.py in __getitem__(self, args)
    257             return self
    258 
--> 259         start, count, step, scalar = _handle_simple(self.shape,args)
    260 
    261         self._id.select_hyperslab(start, count, step)

~/anaconda3/lib/python3.6/site-packages/h5py-2.6.0-py3.6-macosx-10.7-x86_64.egg/h5py/_hl/selections.py in _handle_simple(shape, args)
    445         else:
    446             try:
--> 447                 x,y,z = _translate_int(int(arg), length)
    448                 s = True
    449             except TypeError:

~/anaconda3/lib/python3.6/site-packages/h5py-2.6.0-py3.6-macosx-10.7-x86_64.egg/h5py/_hl/selections.py in _translate_int(exp, length)
    465 
    466     if not 0<=exp<length:
--> 467         raise ValueError("Index (%s) out of range (0-%s)" % (exp, length-1))
    468 
    469     return exp, 1, 1

ValueError: Index (0) out of range (0--1)
```

any ideas/hints/hunches?

**Pull request merged**
