### PR TITLE
updated example brain observatory notebook

### LINKED ISSUE #253: Update read-Allen-Brain-Oservatory notebook
As notebook are usually considered a great source of examples, researchers will often copy snippet as a starting point.

Here are few suggestions to improve them:

* [x] add a cell briefly explaining the different between NWB 1.0 and NWB 2.0. And reference documentation
* [x] select a style. See #251
* [x] re-organize import. See below
* [x] Use print as a function. ``print(foo)`` instead of ``print foo``

### Import order

See https://www.python.org/dev/peps/pep-0008/#imports

Instead of:

```
from allensdk.core.brain_observatory_cache import BrainObservatoryCache
import allensdk.brain_observatory.stimulus_info as si
import warnings
import pynwb
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
```

prefer

```
import warnings

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

import pynwb
from allensdk.core.brain_observatory_cache import BrainObservatoryCache
import allensdk.brain_observatory.stimulus_info as si
```

### PR DESCRIPTION
**Pull request by nicain**
## Motivation

Resolves #253 

## How to test the behavior?
Execute jupyter notebook in py2 and py3

## Checklist

- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR description clearly describes problem and the solution?
- [x] Is your contribution compliant with our coding style ? This can be checked running `flake8` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [x] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ?

### CODE REVIEW

**Comment by nicain** [comment]
@jcfr Removed !pip install from first cell, and replaced with links to install guides.  I think this is good enough for now, and we can talk about further improvements (sphinx-gallery, requirements-notebooks.txt, separate repo) next team meeting.

**Comment by nicain** [comment]
Anybody have any idea why this push failed so badly? All I did was as update the notebook.

**Comment by jcfr** [comment]
While I don't know why, I managed to isolate the checkout code causing trouble from CircleCI log:

```
CIRCLE_REPOSITORY_URL=git@github.com:NeurodataWithoutBorders/pynwb.git
CIRCLE_SHA1=47826cbdff988625c62b3d4dc58d1787ba7bfcd4
CIRCLE_BRANCH=pull/254

mkdir -p /tmp/project
cd /tmp/project
git clone "$CIRCLE_REPOSITORY_URL" .
git fetch --force origin "pull/254/head:remotes/origin/pull/254"
git reset --hard "$CIRCLE_SHA1"    # <------ Failing here 
git checkout -q -B "$CIRCLE_BRANCH"
```

**Comment by oruebel** [comment]
@ncain @jcfr I agree that Jupyter notebook tutorials should be part of our next dev meeting discussions. This topic has come up before in particular with regard to our need to develop more tutorials.  One solution may be for us to have a dedicated repo for creating a Jupyter-based PyNWB codebook so that we can setup requirements, testing etc. independently for the notebooks and to also make the materials we develop more accessible. So far we only have a few notebooks but this will grow so that we'll also need to organize the notebooks more cleanly as well.
CC @ajtritt

**Comment by jcfr** [comment]
@oruebel Makes sense. xref https://github.com/NeurodataWithoutBorders/pynwb/pull/252#issuecomment-343979139

**Comment by nicain** [comment]
Resolves #251

**Pull request merged**
