### PR TITLE
Add trials

### PR DESCRIPTION
**Pull request by ajtritt**
## Motivation

Add support for storing trial data

## How to test the behavior?
```
Will add this eventually
```

## Checklist

- [ ] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [ ] Have you ensured the PR description clearly describes problem and the solution?
- [ ] Is your contribution compliant with our coding style ? This can be checked running `flake8` from the source directory.
- [ ] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [ ] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ?

### CODE REVIEW

**Comment by bendichter** [comment]
@ajtritt This is great. Trials are often going to have features, so I imagine usually using this workflow:

```python
trials = DynamicTable('trials', 'source')
trials.add_column('start', 'the start time of each trial')
trials.add_column('end', 'the end time of each trial')
trials.add_column('direction', 'L or R')
trials.add_column('success', 'bool for if the trials was successful')

tirals.add_row({'start': 30, 'end': 40, 'direction': 'L', 'success': 1})
...

nwbfile.trials = trials
```

as opposed to
```python
nwbfile.add_trial({'start': 30.0, 'end': 40.0})
```
since (as far as I can tell) the latter does not allow for additional columns. The first also allows me to specify multiple trial tables, which I think will be necessary in some datasets.


I would prefer kwargs instead of a `dict` for `trials.add_trial`, but that's not a big deal. Would it be difficult to allow for specifying a `dtype` in `trials.add_column`? It's not essential, but would be nice. Also, it would be nice to specify a `default_val`. Also not essential.

**Comment by bendichter** [comment]
@ajtritt When I create the trials object like this:
```python
trials = DynamicTable('trials', 'source')
features = trialdatainfo[:7]
[trials.add_column(x, 'description') for x in features]

for trial_data in trials_data:
    trials.add_row({lab: dat for lab, dat in zip(features, trial_data[:7])})
```

and try to add them to the file with `nwbfile.trials = trials` I get the following error:

```python
Traceback (most recent call last):
  File "/Users/bendichter/dev/to_nwb/Buzsaki/convert_yuta.py", line 295, in <module>
    nwbfile.trials = trials
  File "/Users/bendichter/dev/pynwb/src/pynwb/core.py", line 195, in nwbdi_setter
    super_setter(self, val)
  File "/Users/bendichter/dev/pynwb/src/pynwb/core.py", line 138, in nwbbt_setter
    raise AttributeError(msg)
AttributeError: can't set attribute 'trials' -- already set
```

I created the trials this way because they needed more columns than just start and end time. How would I add this object to the file?

**Comment by ajtritt** [comment]
@bendichter 

This shouldn't be an issue (you should be able set `nwbfile.trial`). You shouldn't need to do this though, since you can add columns with `NWBFile.add_trial_column`

**Comment by bendichter** [comment]
@ajtritt OK thanks I'll try that out

**Comment by bendichter** [comment]
I'm getting an empty trials table with 

```python
from pynwb import NWBFile, NWBHDF5IO
from datetime import datetime

nwbfile = NWBFile('source', ' ', ' ',
                  datetime.now(), datetime.now(),
                  institution='University of California, San Francisco',
                  lab='Chang Lab')

nwbfile.add_trial({'start': 0., 'end': 1.})

with NWBHDF5IO('test333.nwb', 'w') as io:
    io.write(nwbfile)
```

**Review by bendichter — COMMENTED** [review]
@ajtritt To me, "roundtrip test" would imply writing some example data to disk and then reading it again. Have you created a test like that? Are you planning to? I ask because I am trying to save trials and I am not seeing them in the resulting HDF5 file. Generally I would go to the round-trip test for help in this.

**Comment by ajtritt** [comment]
@bendichter This PR has yet to be merged because I am still working on it. That includes testing.

**Comment by ajtritt** [comment]
@bendichter 

I don't have that issue on my end:

```
(py3) lm:dichter_trials$ cat test.py
from pynwb import NWBFile, NWBHDF5IO
from datetime import datetime

nwbfile = NWBFile('source', ' ', ' ',
                  datetime.now(), datetime.now(),
                  institution='University of California, San Francisco',
                  lab='Chang Lab')

nwbfile.add_trial({'start': 0., 'end': 1.})

with NWBHDF5IO('test333.nwb', 'w') as io:
    io.write(nwbfile)
(py3) lm:dichter_trials$ python test.py
/Users/ajtritt/anaconda/envs/py3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
(py3) lm:dichter_trials$ h5ls test333.nwb/trials
end                      Dataset {1}
id                       Dataset {1}
start                    Dataset {1}
```

Can you update and try again?

**Comment by bendichter** [comment]
@ajtritt Yeah it works for me now, thanks. I may not have updated or something before.

**Comment by bendichter** [comment]
however now I have an error when I run my large conversion script:

```python
Traceback (most recent call last):
  File "/Users/bendichter/dev/to_nwb/Buzsaki/convert_yuta.py", line 297, in <module>
    io.write(nwbfile)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py", line 178, in write
    call_docval_func(super(HDF5IO, self).write, kwargs)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 230, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/backends/io.py", line 39, in write
    f_builder = self.__manager.build(container, source=self.__source)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 135, in build
    result = self.__type_map.build(container, self, source=source)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1192, in build
    builder = attr_map.build(container, manager, builder=builder, source=getargs('source', kwargs))
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 584, in build
    self.__add_groups(builder, self.__spec.groups, container, manager, source)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 708, in __add_groups
    self.__add_groups(sub_builder, spec.groups, container, build_manager, source)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 724, in __add_groups
    self.__add_containers(builder, spec, attr_value, build_manager, source, container)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 758, in __add_containers
    self.__add_containers(builder, spec, container, build_manager, source, parent_container)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 732, in __add_containers
    rendered_obj = build_manager.build(value, source=source)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 135, in build
    result = self.__type_map.build(container, self, source=source)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1192, in build
    builder = attr_map.build(container, manager, builder=builder, source=getargs('source', kwargs))
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 583, in build
    self.__add_datasets(builder, self.__spec.datasets, container, manager, source)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 672, in __add_datasets
    if attr_value is None or len(attr_value) == 0:
TypeError: object of type 'H5DataIO' has no len()
```

The script that I run is long and expects data:

```python
import os
from functools import partialmethod

from datetime import datetime
import numpy as np
from scipy.io import loadmat
from dateutil.parser import parse as dateparse
import pandas as pd

from pynwb import NWBFile, NWBHDF5IO
from pynwb.file import Subject
from pynwb.behavior import SpatialSeries, Position
from pynwb.ecephys import ElectricalSeries, LFP

from utils import find_discontinuities
import neuroscope as ns
from general import CatCellInfo

from pynwb.form.backends.hdf5 import H5DataIO as gzip
gzip.__init__ = partialmethod(gzip.__init__, compression='gzip')

WRITE_ALL_LFPS = False


fpath = '/Users/bendichter/Desktop/Buzsaki/SenzaiBuzsaki2017/YutaMouse41-150903'
subject_fpath = '/Users/bendichter/Desktop/Buzsaki/SenzaiBuzsaki2017/YM41 exp_sheet.xlsx'
fpath_base, fname = os.path.split(fpath)
identifier = fname

subject_id, date_text = fname.split('-')
session_start_time = dateparse(date_text, yearfirst=True)

df = pd.read_excel(subject_fpath)

subject_data = {}
for key in ['genotype', 'DOB', 'implantation', 'Probe']:
    subject_data[key] = df.ix[df.ix[:, 0] == key, 1].values[0]

age = session_start_time - subject_data['DOB']

subject = Subject(subject_id=subject_id, age=str(age),
                  genotype=subject_data['genotype'],
                  species='mouse', source='source')

source = fname
nwbfile = NWBFile(source=source,
                  session_description='mouse in open exploration and theta maze',
                  identifier=identifier,
                  session_start_time=session_start_time,
                  file_create_date=datetime.now(),
                  experimenter='Yuta Senzai',
                  session_id=fname,
                  institution='NYU',
                  lab='Buzsaki',
                  subject=subject,
                  related_publications='DOI:10.1016/j.neuron.2016.12.011')

all_ts = []

xml_filepath = os.path.join(fpath, fname + '.xml')

channel_groups = ns.get_channel_groups(xml_filepath)
shank_channels = ns.get_shank_channels(xml_filepath)
nshanks = len(shank_channels)
all_shank_channels = np.concatenate(shank_channels)
nchannels = sum(len(x) for x in channel_groups)
lfp_fs = ns.get_lfp_sampling_rate(xml_filepath)

lfp_channel = 0  # value taken from Yuta's spreadsheet

print('reading raw position data...', end='', flush=True)
pos_df = ns.get_position_data(fpath, fname)
print('done.')

print('setting up raw position data...', end='', flush=True)
# raw position sensors file
pos0 = nwbfile.add_acquisition(
    SpatialSeries('position sensor0',
                  'raw sensor data from sensor 0',
                  gzip(pos_df[['x0', 'y0']].values),
                  'unknown',
                  timestamps=gzip(pos_df.index.values),
                  resolution=np.nan))
all_ts.append(pos0)

pos1 = nwbfile.add_acquisition(
    SpatialSeries('position sensor1',
                  'raw sensor data from sensor 1',
                  gzip(pos_df[['x1', 'y1']].values),
                  'unknown',
                  timestamps=gzip(pos_df.index.values),
                  resolution=np.nan))
all_ts.append(pos1)
print('done.')

print('setting up electrodes...', end='', flush=True)
# shank electrodes
electrode_counter = 0
for shankn, channels in enumerate(shank_channels):
    device_name = 'shank{}'.format(shankn)
    device = nwbfile.create_device(device_name, fname + '.xml')
    electrode_group = nwbfile.create_electrode_group(
        name=device_name + '_electrodes',
        source=fname + '.xml',
        description=device_name,
        device=device,
        location='unknown')
    for channel in channels:
        nwbfile.add_electrode(channel,
                              np.nan, np.nan, np.nan,  # position?
                              imp=np.nan,
                              location='unknown',
                              filtering='unknown',
                              description='electrode {} of shank {}, channel {}'.format(
                                  electrode_counter, shankn, channel),
                              group=electrode_group)

        if channel == lfp_channel:
            lfp_table_region = nwbfile.create_electrode_table_region(
                [electrode_counter], 'lfp electrode')

        electrode_counter += 1

# special electrodes
device_name = 'special'
device = nwbfile.create_device(device_name, fname + '.xml')
electrode_group = nwbfile.create_electrode_group(
    name=device_name + '_electrodes',
    source=fname + '.xml',
    description=device_name,
    device=device,
    location='unknown')
special_electrode_dict = {'ch_wait': 79, 'ch_arm': 78, 'ch_solL': 76,
                          'ch_solR': 77, 'ch_dig1': 65, 'ch_dig2': 68,
                          'ch_entL': 72, 'ch_entR': 71, 'ch_SsolL': 73,
                          'ch_SsolR': 70}
for name, num in special_electrode_dict.items():
    nwbfile.add_electrode(num,
                          np.nan, np.nan, np.nan,
                          imp=np.nan,
                          location='unknown',
                          filtering='unknown',
                          description=name,
                          group=electrode_group)
    nwbfile.create_electrode_table_region([electrode_counter], name)
    electrode_counter += 1

all_table_region = nwbfile.create_electrode_table_region(
    list(range(electrode_counter)), 'all electrodes')
print('done.')

# lfp
print('reading LFPs...', end='', flush=True)
lfp_file = os.path.join(fpath, fname + '.lfp')
#all_channels = np.fromfile(lfp_file, dtype=np.int16).reshape(-1, 80)
all_channels = np.random.randn(1000,100)
all_channels_lfp = all_channels[:, all_shank_channels]
print('done.')

if WRITE_ALL_LFPS:
    data = gzip(all_channels_lfp)
else:
    data = gzip(all_channels_lfp[:100])

print('making ElectricalSeries objects for LFP...', end='', flush=True)
all_lfp = nwbfile.add_acquisition(
    ElectricalSeries('all_lfp',
                     'lfp signal for all shank electrodes',
                     data,
                     all_table_region,
                     conversion=np.nan,
                     starting_time=0.0,
                     rate=lfp_fs,
                     resolution=np.nan))
all_ts.append(all_lfp)
print('done.')


electrical_series = ElectricalSeries(
            'reference lfp',
            'signal used as the reference lfp',
            gzip(all_channels[:, lfp_channel]),
            lfp_table_region,
            conversion=np.nan,
            starting_time=0.0,
            rate=lfp_fs,
            resolution=np.nan)
lfp = nwbfile.add_acquisition(LFP(source='source',
                                  electrical_series=electrical_series))
all_ts.append(electrical_series)

# create epochs corresponding to experiments/environments for the mouse
task_types = ['OpenFieldPosition_ExtraLarge', 'OpenFieldPosition_New_Curtain',
              'OpenFieldPosition_New', 'OpenFieldPosition_Old_Curtain',
              'OpenFieldPosition_Old', 'OpenFieldPosition_Oldlast']

module_behavior = nwbfile.create_processing_module(name='behavior',
                                                   source=source,
                                                   description=source)
for label in task_types:
    print('loading normalized position data for ' + label + '...', end='', flush=True)
    file = os.path.join(fpath, fname + '__' + label)

    matin = loadmat(file)
    tt = matin['twhl_norm'][:, 0]
    pos_data = matin['twhl_norm'][:, 1:3]

    exp_times = find_discontinuities(tt)

    spatial_series_object = SpatialSeries(name=label + ' spatial_series',
                                          source='position sensor0',
                                          data=gzip(pos_data),
                                          reference_frame='unknown',
                                          conversion=np.nan,
                                          resolution=np.nan,
                                          timestamps=gzip(tt))
    pos_obj = Position(source=source,
                       spatial_series=spatial_series_object,
                       name=label + '_position')

    module_behavior.add_container(pos_obj)

    for i, window in enumerate(exp_times):
        nwbfile.create_epoch(start_time=window[0], stop_time=window[1],
                         tags=tuple(), description=label + '_' + str(i),
                         timeseries=all_ts+[spatial_series_object])
    print('done.')

## load celltypes
matin = loadmat(os.path.join(fpath_base, 'DG_all_6__UnitFeatureSummary_add.mat'),
                struct_as_record=False)['UnitFeatureCell'][0][0]

# taken from ReadMe
celltype_dict = {
    0: 'unknown',
    1: 'granule cells (DG) or pyramidal cells (CA3)  (need to use region info. see below.)',
    2: 'mossy cell',
    3: 'narrow waveform cell',
    4: 'optogenetically tagged SST cell',
    5: 'wide waveform cell (narrower, exclude opto tagged SST cell)',
    6: 'wide waveform cell (wider)',
    8: 'positive waveform unit (non-bursty)',
    9: 'positive waveform unit (bursty)',
    10: 'positive negative waveform unit'
}

region_dict = {3: 'CA3', 4: 'DG'}

this_file = matin.fname == fname
celltype_ids = matin.fineCellType.ravel()[this_file]
region_ids = matin.region.ravel()[this_file]
unit_ids = matin.unitID.ravel()[this_file]

celltype_names = []
for celltype_id, region_id in zip(celltype_ids, region_ids):
    if celltype_id == 1:
        if region_id == 3:
            celltype_names.append('pyramidal cell')
        elif region_id == 4:
            celltype_names.append('granule cell')
        else:
            raise Exception('unknown type')
    else:
        celltype_names.append(celltype_dict[celltype_id])

u_cats, indices = np.unique(celltype_names, return_inverse=True)

cci_obj = CatCellInfo(name='CellTypes',
                      source='DG_all_6__UnitFeatureSummary_add.mat',
                      values=list(u_cats), indices=list(indices))

ut_obj = ns.build_unit_times(fpath, fname)

module_spikes = nwbfile.create_processing_module('spikes', source=source,
                                                 description=source)

module_spikes.add_container(ut_obj)
module_spikes.add_container(cci_obj)

trialdata_path = os.path.join(fpath, fname + '__EightMazeRun.mat')
trials_data = loadmat(trialdata_path)['EightMazeRun']

trialdatainfo_path = os.path.join(fpath, fname + '__EightMazeRunInfo.mat')
trialdatainfo = [x[0] for x in loadmat(trialdatainfo_path)['EightMazeRunInfo'][0]]


features = trialdatainfo[:7]
[nwbfile.add_trial_column(x, 'description') for x in features]

for trial_data in trials_data:
    nwbfile.add_trial({lab: dat for lab, dat in zip(features, trial_data[:7])})


out_fname = fname + '.nwb'
print('writing NWB file...', end='', flush=True)
with NWBHDF5IO(out_fname, mode='w') as io:
    io.write(nwbfile)
print('done.')

print('testing read...', end='', flush=True)
# test read
with NWBHDF5IO(out_fname, mode='r') as io:
    io.read()
print('done.')
```

I'll try to work on a minimal example that reproduces this error

**Comment by bendichter** [comment]
Here's a minimal example of a similar error:

```python
from pynwb import NWBFile, NWBHDF5IO, TimeSeries
from datetime import datetime

nwbfile = NWBFile('source', ' ', ' ',
                  datetime.now(), datetime.now(),
                  institution='University of California, San Francisco',
                  lab='Chang Lab')

nwbfile.add_acquisition(TimeSeries(data=[1., 2., 3.], starting_time=0.0, rate=100.,
                                   unit='V', name='name', source='source'))

with NWBHDF5IO('test333.nwb', 'w') as io:
    io.write(nwbfile)
```

```python
Traceback (most recent call last):
  File "/Users/bendichter/dev/to_nwb/chang/test_trials.py", line 14, in <module>
    io.write(nwbfile)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py", line 178, in write
    call_docval_func(super(HDF5IO, self).write, kwargs)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 230, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/backends/io.py", line 39, in write
    f_builder = self.__manager.build(container, source=self.__source)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 135, in build
    result = self.__type_map.build(container, self, source=source)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1192, in build
    builder = attr_map.build(container, manager, builder=builder, source=getargs('source', kwargs))
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 584, in build
    self.__add_groups(builder, self.__spec.groups, container, manager, source)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 708, in __add_groups
    self.__add_groups(sub_builder, spec.groups, container, build_manager, source)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 724, in __add_groups
    self.__add_containers(builder, spec, attr_value, build_manager, source, container)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 758, in __add_containers
    self.__add_containers(builder, spec, container, build_manager, source, parent_container)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 732, in __add_containers
    rendered_obj = build_manager.build(value, source=source)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 135, in build
    result = self.__type_map.build(container, self, source=source)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1192, in build
    builder = attr_map.build(container, manager, builder=builder, source=getargs('source', kwargs))
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 583, in build
    self.__add_datasets(builder, self.__spec.datasets, container, manager, source)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 672, in __add_datasets
    if attr_value is None or len(attr_value) == 0:
TypeError: object of type 'float' has no len()
```

**Comment by ajtritt** [comment]
You need to update your local copy or straighten out your environment.... This is what line 672 of that file looks like:

https://github.com/NeurodataWithoutBorders/pynwb/blob/1496a99fefb89473e05768015339fd68ff9edeee/src/pynwb/form/build/map.py#L672

It might help if you start from a [fresh conda environment](https://conda.io/docs/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands) and then clone a fresh version of the [enh/trials](https://github.com/NeurodataWithoutBorders/pynwb/tree/enh/trials) branch

**Comment by bendichter** [comment]
hmm ok good to know. I did notice that there was a merge from enh/trials with enh/trials and I was a bit confused about that. Let me try something a little less drastic and see if that fixes the issue.

**Comment by bendichter** [comment]
@ajtritt It works! Thanks so much for all the help!

**Review by oruebel — APPROVED** [review]

**Pull request merged**
