### PR TITLE
Make source_timeseries a required argument

### LINKED ISSUE #951: reading a file that contains a DecompositionSeries raises KeyError: 'source_timeseries'
## 1) Bug
I believe this to be a bug. I’m trying to add a DecompositionSeries to a file and it seems to be saving it alright. When opening the updated file, however, it raises an error.

### Steps to Reproduce
```python
from datetime import datetime
from dateutil.tz import tzlocal
from pynwb import NWBFile, TimeSeries, NWBHDF5IO, ProcessingModule
from pynwb.ecephys import LFP
from pynwb.core import DynamicTable, DynamicTableRegion, VectorData
from pynwb.misc import DecompositionSeries
import numpy as np

nSamples = 100
nChannels = 10
nBands = 5

# Create a new NWB file
start_time = datetime(2017, 4, 3, 11, tzinfo=tzlocal())

nwb = NWBFile(session_description='demonstrate NWBFile basics',
              identifier='NWB123',  
              session_start_time=start_time)  

# Add signal
X_data = np.zeros((nChannels,nSamples))
timestamps = list(range(nSamples))
test_ts = TimeSeries(name='test_timeseries', data=X_data, unit='s', timestamps=timestamps)
nwb.add_acquisition(test_ts)

# Add electrode groups and channels
dev0 = nwb.create_device(name='dev0')
elec_group0 = nwb.create_electrode_group(name='electrodes', description='', location='', device=dev0)
for i in np.arange(nChannels):
    ii = float(i)
    nwb.add_electrode(x=ii, y=ii, z=ii, imp=ii, location='', filtering='', group=elec_group0)

io = NWBHDF5IO('example_file.nwb', mode='w')
io.write(nwb)
io.close()


# Now open and write new data to file
with NWBHDF5IO('example_file.nwb', 'r+') as io:
    nwb = io.read()

    # Create LFP data interface container
    lfp = LFP()

    # Add preprocessed downsampled signals as an electrical_series
    elecs_region = nwb.electrodes.create_region(name='electrodes', 
                                                region=np.arange(10).tolist(), 
                                                description='')
    X_data = np.zeros((nChannels,nSamples))
    lfp.create_electrical_series(name='preprocessed',
                                 data=X_data,
                                 electrodes=elecs_region,
                                 rate=1.,
                                 description='no description')

    # Add spectral band power as a decomposition_series
    # bands: (DynamicTable) a table for describing the frequency bands that the signal was decomposed into
    cfsV = VectorData(name='filter_center',
                      description='frequencies for bandpass filters',
                      data=np.arange(nBands))
    sdsV = VectorData(name='filter_sigma',
                      description='frequencies for bandpass filters',
                      data=np.arange(nBands))
    bandsTable = DynamicTable(name='bands',
                              description='Series of filters used for Hilbert transform.',
                              columns=[cfsV,sdsV],
                              colnames=['filter_center','filter_sigma'])

    # data: (ndarray) dims: num_times * num_channels * num_bands
    Xp = np.zeros((nSamples,nChannels,nBands))
    decs = DecompositionSeries(name='Bandpower',
                                data=Xp,
                                description='Band power estimated with Hilbert transform.',
                                metric='power',
                                unit='V**2/Hz',
                                bands=bandsTable,
                                rate=1.)

    # Create ecephys ProcessingModule
    ecephys_module = ProcessingModule(name='ecephys',
                                      description='Extracellular electrophysiology data.')

    # Add LFP data interface container to ecephys ProcessingModule
    ecephys_module.add_data_interface(lfp)
    ecephys_module.add_data_interface(decs)

    # Add module to NWB file
    nwb.add_processing_module(ecephys_module)

    io.write(nwb)
    
    print('Data do be written')
    print(nwb.modules['ecephys'].data_interfaces['Bandpower'])
    

# Now open the re-written file and check it's content
with NWBHDF5IO('example_file.nwb', 'r') as io:
    nwb = io.read()
    print('Read written data')
    print(nwb.modules['ecephys'].data_interfaces['Bandpower'])
```

This gives:
```
Data do be written

Bandpower <class 'pynwb.misc.DecompositionSeries'>
Fields:
  bands: bands <class 'pynwb.core.DynamicTable'>
  comments: no comments
  conversion: 1.0
  data: [[[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  ..., 
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  ..., 
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  ..., 
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 ..., 
 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  ..., 
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  ..., 
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  ..., 
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]]
  description: Band power estimated with Hilbert transform.
  metric: power
  num_samples: 100
  rate: 1.0
  resolution: 0.0
  starting_time: 0.0
  unit: V**2/Hz

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-18-e067c66857b7> in <module>
     96 # Now open the re-written file and check it's content
     97 with NWBHDF5IO('example_file.nwb', 'r') as io:
---> 98     nwb = io.read()
     99     print('Read written data')
    100     print(nwb.modules['ecephys'].data_interfaces['Bandpower'])

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/utils.py in func_call(*args, **kwargs)
    386                         raise_from(ExceptionType(msg), None)
    387 
--> 388                 return func(self, **parsed['args'])
    389         else:
    390             def func_call(*args, **kwargs):

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/backends/io.py in read(self, **kwargs)
     31     def read(self, **kwargs):
     32         f_builder = self.read_builder()
---> 33         container = self.__manager.construct(f_builder)
     34         return container
     35 

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/utils.py in func_call(*args, **kwargs)
    386                         raise_from(ExceptionType(msg), None)
    387 
--> 388                 return func(self, **parsed['args'])
    389         else:
    390             def func_call(*args, **kwargs):

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/build/map.py in construct(self, **kwargs)
    198         result = self.__containers.get(builder_id)
    199         if result is None:
--> 200             result = self.__type_map.construct(builder, self)
    201             parent_builder = self.__get_parent_dt_builder(builder)
    202             if parent_builder is not None:

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/utils.py in func_call(*args, **kwargs)
    386                         raise_from(ExceptionType(msg), None)
    387 
--> 388                 return func(self, **parsed['args'])
    389         else:
    390             def func_call(*args, **kwargs):

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/build/map.py in construct(self, **kwargs)
   1631             raise ValueError('No ObjectMapper found for builder of type %s' % dt)
   1632         else:
-> 1633             return attr_map.construct(builder, build_manager)
   1634 
   1635     @docval({"name": "container", "type": Container, "doc": "the container to convert to a Builder"},

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/utils.py in func_call(*args, **kwargs)
    386                         raise_from(ExceptionType(msg), None)
    387 
--> 388                 return func(self, **parsed['args'])
    389         else:
    390             def func_call(*args, **kwargs):

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/build/map.py in construct(self, **kwargs)
   1179         cls = manager.get_cls(builder)
   1180         # gather all subspecs
-> 1181         subspecs = self.__get_subspec_values(builder, self.spec, manager)
   1182         # get the constructor argument that each specification corresponds to
   1183         const_args = dict()

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/build/map.py in __get_subspec_values(self, builder, spec, manager)
   1123                         ret[subspec] = self.__flatten(sub_builder, subspec, manager)
   1124             # now process groups and datasets
-> 1125             self.__get_sub_builders(groups, spec.groups, manager, ret)
   1126             self.__get_sub_builders(datasets, spec.datasets, manager, ret)
   1127         elif isinstance(spec, DatasetSpec):

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/build/map.py in __get_sub_builders(self, sub_builders, subspecs, manager, ret)
   1161                 if dt is None:
   1162                     # recurse
-> 1163                     ret.update(self.__get_subspec_values(sub_builder, subspec, manager))
   1164                 else:
   1165                     ret[subspec] = manager.construct(sub_builder)

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/build/map.py in __get_subspec_values(self, builder, spec, manager)
   1123                         ret[subspec] = self.__flatten(sub_builder, subspec, manager)
   1124             # now process groups and datasets
-> 1125             self.__get_sub_builders(groups, spec.groups, manager, ret)
   1126             self.__get_sub_builders(datasets, spec.datasets, manager, ret)
   1127         elif isinstance(spec, DatasetSpec):

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/build/map.py in __get_sub_builders(self, sub_builders, subspecs, manager, ret)
   1153                 sub_builder = builder_dt.get(dt)
   1154                 if sub_builder is not None:
-> 1155                     sub_builder = self.__flatten(sub_builder, subspec, manager)
   1156                     ret[subspec] = sub_builder
   1157             else:

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/build/map.py in __flatten(self, sub_builder, subspec, manager)
   1166 
   1167     def __flatten(self, sub_builder, subspec, manager):
-> 1168         tmp = [manager.construct(b) for b in sub_builder]
   1169         if len(tmp) == 1 and not subspec.is_many():
   1170             tmp = tmp[0]

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/build/map.py in <listcomp>(.0)
   1166 
   1167     def __flatten(self, sub_builder, subspec, manager):
-> 1168         tmp = [manager.construct(b) for b in sub_builder]
   1169         if len(tmp) == 1 and not subspec.is_many():
   1170             tmp = tmp[0]

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/utils.py in func_call(*args, **kwargs)
    386                         raise_from(ExceptionType(msg), None)
    387 
--> 388                 return func(self, **parsed['args'])
    389         else:
    390             def func_call(*args, **kwargs):

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/build/map.py in construct(self, **kwargs)
    198         result = self.__containers.get(builder_id)
    199         if result is None:
--> 200             result = self.__type_map.construct(builder, self)
    201             parent_builder = self.__get_parent_dt_builder(builder)
    202             if parent_builder is not None:

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/utils.py in func_call(*args, **kwargs)
    386                         raise_from(ExceptionType(msg), None)
    387 
--> 388                 return func(self, **parsed['args'])
    389         else:
    390             def func_call(*args, **kwargs):

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/build/map.py in construct(self, **kwargs)
   1631             raise ValueError('No ObjectMapper found for builder of type %s' % dt)
   1632         else:
-> 1633             return attr_map.construct(builder, build_manager)
   1634 
   1635     @docval({"name": "container", "type": Container, "doc": "the container to convert to a Builder"},

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/utils.py in func_call(*args, **kwargs)
    386                         raise_from(ExceptionType(msg), None)
    387 
--> 388                 return func(self, **parsed['args'])
    389         else:
    390             def func_call(*args, **kwargs):

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/build/map.py in construct(self, **kwargs)
   1179         cls = manager.get_cls(builder)
   1180         # gather all subspecs
-> 1181         subspecs = self.__get_subspec_values(builder, self.spec, manager)
   1182         # get the constructor argument that each specification corresponds to
   1183         const_args = dict()

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/build/map.py in __get_subspec_values(self, builder, spec, manager)
   1123                         ret[subspec] = self.__flatten(sub_builder, subspec, manager)
   1124             # now process groups and datasets
-> 1125             self.__get_sub_builders(groups, spec.groups, manager, ret)
   1126             self.__get_sub_builders(datasets, spec.datasets, manager, ret)
   1127         elif isinstance(spec, DatasetSpec):

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/build/map.py in __get_sub_builders(self, sub_builders, subspecs, manager, ret)
   1153                 sub_builder = builder_dt.get(dt)
   1154                 if sub_builder is not None:
-> 1155                     sub_builder = self.__flatten(sub_builder, subspec, manager)
   1156                     ret[subspec] = sub_builder
   1157             else:

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/build/map.py in __flatten(self, sub_builder, subspec, manager)
   1166 
   1167     def __flatten(self, sub_builder, subspec, manager):
-> 1168         tmp = [manager.construct(b) for b in sub_builder]
   1169         if len(tmp) == 1 and not subspec.is_many():
   1170             tmp = tmp[0]

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/build/map.py in <listcomp>(.0)
   1166 
   1167     def __flatten(self, sub_builder, subspec, manager):
-> 1168         tmp = [manager.construct(b) for b in sub_builder]
   1169         if len(tmp) == 1 and not subspec.is_many():
   1170             tmp = tmp[0]

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/utils.py in func_call(*args, **kwargs)
    386                         raise_from(ExceptionType(msg), None)
    387 
--> 388                 return func(self, **parsed['args'])
    389         else:
    390             def func_call(*args, **kwargs):

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/build/map.py in construct(self, **kwargs)
    198         result = self.__containers.get(builder_id)
    199         if result is None:
--> 200             result = self.__type_map.construct(builder, self)
    201             parent_builder = self.__get_parent_dt_builder(builder)
    202             if parent_builder is not None:

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/utils.py in func_call(*args, **kwargs)
    386                         raise_from(ExceptionType(msg), None)
    387 
--> 388                 return func(self, **parsed['args'])
    389         else:
    390             def func_call(*args, **kwargs):

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/build/map.py in construct(self, **kwargs)
   1631             raise ValueError('No ObjectMapper found for builder of type %s' % dt)
   1632         else:
-> 1633             return attr_map.construct(builder, build_manager)
   1634 
   1635     @docval({"name": "container", "type": Container, "doc": "the container to convert to a Builder"},

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/utils.py in func_call(*args, **kwargs)
    386                         raise_from(ExceptionType(msg), None)
    387 
--> 388                 return func(self, **parsed['args'])
    389         else:
    390             def func_call(*args, **kwargs):

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/build/map.py in construct(self, **kwargs)
   1179         cls = manager.get_cls(builder)
   1180         # gather all subspecs
-> 1181         subspecs = self.__get_subspec_values(builder, self.spec, manager)
   1182         # get the constructor argument that each specification corresponds to
   1183         const_args = dict()

~/anaconda3/envs/ecog_vis/lib/python3.6/site-packages/hdmf/build/map.py in __get_subspec_values(self, builder, spec, manager)
   1117             for subspec in spec.links:
   1118                 if subspec.name is not None:
-> 1119                     ret[subspec] = manager.construct(links[subspec.name].builder)
   1120                 else:
   1121                     sub_builder = link_dt.get(subspec.target_type)

KeyError: 'source_timeseries'
```

As you can see, the data seem to be stored (the file size increases proportionally also), but it creates a problem when reading the file. I’m sure the problem is with the DecompositionSeries because, if I comment the line `ecephys_module.add_data_interface(decs)` and don’t include it, the file will open without problems.
I also tried `ecephys_module.add_container(decs)`, it raises the same error.

### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Conda
- **Python Version:** Python 3.6
- **Operating System:** Linux
- **Pynwb Version:** 1.0.2

## Checklist
- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

### PR DESCRIPTION
**Pull request by oruebel**
Fix #951 

The spec for DecompositionSeries requires ``source_timeseries`` but the container class specifies a default of None. This leads to an error on read because the required field is not found. This makes source_timeseries required on the container to be consistent with the schema.

## Checklist

- [X] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured the PR description clearly describes problem and the solution?
- [X] Is your contribution compliant with our coding style ? This can be checked running `flake8` from the source directory.
- [X] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [X] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ?

### CODE REVIEW

**Comment by bendichter** [comment]
Should be change the schema instead? What if we don't have the source timeseries in the file?

**Comment by oruebel** [comment]
> Should be change the schema instead?

That's fine. But I think we should raise a warning if users do not specify ``source_timeseries`` because it is an important piece of information and if possible folks should specify it rather than ignore it.

**Comment by bendichter** [comment]
it appears there is no way to specify that a link is optional (https://schema-language.readthedocs.io/en/latest/specification_language_description.html#link-specification-keys). Am I reading this right?

**Comment by bendichter** [comment]
it looks like "quantity" can be used:

https://github.com/NeurodataWithoutBorders/pynwb/blob/8f472d6c5b74a72e57073fca4c8100a60dfc16a1/src/pynwb/data/nwb.ecephys.yaml#L338-L342

**Comment by oruebel** [comment]
> it looks like "quantity" can be used:

Yes, the ``LinkSpec`` class supports it as well, so this should be fine. I'll update the spec-language docs accordingly.

**Comment by oruebel** [comment]
Superseded by #955

**Pull request closed without merging**
