### PR TITLE
Change to appropriate github URL

### LINKED ISSUE #517: Update extension docs to point to nwb-docutils
## 1) Bug

The tutorial on creating extensions here 

http://pynwb.readthedocs.io/en/latest/extensions.html#documenting-extensions

points to documentation tools in the nwb-schema repo. As these tools have moved to the [nwb-docutils](https://github.com/NeurodataWithoutBorders/nwb-docutils) repo the docs need to be updated accordingly. 

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [ ] Have you included a minimal code snippet that reproduces the issue you are encountering?

### PR DESCRIPTION
**Pull request by mamelara**
Resolves #517

I'm assuming that's the link you meant?
## Motivation

Accurate docs is good.

## How to test the behavior?
sphinx doctests

## Checklist

- [X] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured the PR description clearly describes problem and the solution?
- [X] Is your contribution compliant with our coding style ? This can be checked running `flake8` from the source directory.
- [X] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [X] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ?

### CODE REVIEW

**Comment by oruebel** [comment]
Thanks for looking at this. This is not quite the right fix. I think what needs to be changed for this issue is:

1) Add a box with ``pip install nwb-docutils``
2) Remove the line ``nwb_schema (cloned from `https://github.com/NeurodataWithoutBorders/nwb-schema`)``
3) Instead of ``python3 nwb-schema/docs/utils/init_sphinx_extension_doc.py`` it should be ``nwb_init_sphinx_extension_doc`` 

I think that should be all the changes but I would need to run through the steps of the example to tests that's it.

**Comment by mamelara** [comment]
Added those changes. BTW there seems to be an issue with sphinx v1.7 and api-docs[1] so I couldn't run `make html` and check whether the formatting was correct.

[1] https://github.com/rtfd/readthedocs.org/issues/1139#issuecomment-398083449

**Comment by oruebel** [comment]
> BTW there seems to be an issue with sphinx v1.7 and api-docs

Yes that is a bit of an annoying problem. On ReadTheDocs we had to pin the sphinx version to work around this problem. https://github.com/NeurodataWithoutBorders/pynwb/pull/397

**Comment by oruebel** [comment]
Few more fixes:
* Can you move ``pip install nwb-docutils`` up before the previous sentence
* Can you change:

```
- nwb_schema
  - my_extension/```

to 

```
  - my_extension/
```

```nwb_schema``` should not be required any more.

**Comment by mamelara** [comment]
@oruebel can you reformat your last comment. It's unclear what you want me to write in the docs. Thanks!

**Comment by mamelara** [comment]
@oruebel I'd like to at least make sure I can get this fix in without falling into the rabbit hole of documentation, so just let me know what exactly you want. Thanks!

**Pull request merged**
