### PR TITLE
Conda on CircleCI

### PR DESCRIPTION
**Pull request by dorukozturk**
## Motivation

Make CI process faster by running conda tests on circle.

@ajtritt Before Appveyor took approximately 30 minutes and now it takes around 10.

### CODE REVIEW

**Comment by mgrauer** [comment]
@dorukozturk Why no miniconda 3.5 in circle?

**Comment by dorukozturk** [comment]
@mgrauer I could not find a pre-baked docker image for miniconda 3.5. The official ones were 2.7 and 3.6. I will try to find one with 3.5.

**Comment by dorukozturk** [comment]
@mgrauer I added miniconda 3.5.

**Comment by mgrauer** [comment]
LGTM, thanks @dorukozturk .

**Review by mgrauer — APPROVED** [review]

**Comment by jcfr** [comment]
Thanks @dorukozturk  👍

**Pull request merged**
