### PR TITLE
ci: Run each test-suite independently and label associated coverage report

### PR DESCRIPTION
**Pull request by jcfr**
See #159

Suggested-by: Andrew Tritt <ajtritt@lbl.gov>

### CODE REVIEW

**Comment by jcfr** [comment]
Look like the python implementation of `codecov` CLI does not support the `-C` parameter. See https://docs.codecov.io/docs/flags

**Comment by jcfr** [comment]
For each tile, there is now a list of toggle button associated with each flags:

ci-coverage-toggle

**Comment by jcfr** [comment]
That said, I suspect we need to clean up the previous coverage report between each run of test suite.

This is available in the bash implementation of the codecov client but not in the python one

**Review by dorukozturk — APPROVED** [review]

**Comment by jcfr** [comment]
Also, it look like I am not authorized to merge pull request.

Would it be possible to grant me the right or proceed with the merge .. thanks

**Pull request merged**
