### PR TITLE
Add documentation example for DecompositionSeries

### LINKED ISSUE #1938: [Documentation]: add documentation example for DecompositionSeries
### What would you like changed or added to the documentation and why?

As discussed in the NWB meeting today, `DecompositionSeries` is not well documented.

[DecompositionSeries](https://nwb-schema.readthedocs.io/en/latest/format.html#decompositionseries) is meant to store spectral analysis of a time series (e.g., different frequency bands of an LFP signal).

I propose we add a short example to the [LFP section](https://pynwb.readthedocs.io/en/stable/tutorials/domain/ecephys.html#lfp) of the Extracellular Electrophysiology Data tutorial demonstrating how to use this data type.

### Do you have any interest in helping write or edit the documentation?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

### PR DESCRIPTION
**Pull request by stephprince**
## Motivation

Fix https://github.com/NeurodataWithoutBorders/pynwb/issues/1938.

~~Note that this example is pending these schema updates: https://github.com/NeurodataWithoutBorders/nwb-schema/pull/593, which make `band_mean` and `band_std` optional.~~

## How to test the behavior?
```
cd docs
make clean && make html
```

## Checklist

- [x] Did you update CHANGELOG.md with your changes?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR clearly describes the problem and the solution?
- [x] Is your contribution compliant with our coding style? This can be checked running `ruff check . && codespell` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [x] Have you included the relevant issue number using "Fix #XXX" notation where XXX is the issue number? By including "Fix #XXX" you allow GitHub to close issue #XXX when the PR is merged.

### CODE REVIEW

**Comment by ehennestad** [comment]
Hi @stephprince. I replicated this example in the ecephys tutorial for matnwb and then I ran nwbinspector on the output file. The nwbinspector errored out before generating the results with the following error: 
`TypeError: 'MissingDataType' object is not iterable`. 
The nwbinspector works fine prior to adding the DecompositionSeries to the nwb file.

I thought it was something matnwb specific, but got the same issue when running nwb inspector on the output of the pynwb tutorial with the new DecompositionSeries example. Could you check if you see the same?

**Comment by stephprince** [comment]
@ehennestad which version of the schema were you using?

I'm waiting to merge this until we release version 2.8.0 of the schema, because this current example will generate invalid files until `band_mean` and `band_stdev` are made to be optional columns on the `DecompositionSeries.bands`table. 

I get the same error as you with the current example + schema, but the inspector should run ok on the file if you change the code to be:

```python
for band_name, band_limits in bands.items():
    decomp_series.add_band(band_name=band_name, band_limits=band_limits, band_mean=1.0, band_stdev=1.0)
```

but I don't think `band_mean` or `band_stdev` are applicable in many cases so ideally we would wait until the next schema release (which should be happening in the next week).

**Comment by ehennestad** [comment]
I was using v2.7.0. Thanks for pointing that out again about the extra required properties. I had tried to add them, but found a typo and after correcting that, it works!

**Comment by stephprince** [comment]
@rly I've updated the example to add the required `band_mean` and `band_stdev` columns as nans so that the tutorial generates valid files using schema v2.7.0 (though it violates best practice suggestions by having a column of all nans).

Once schema v2.8.0 is released, we can update this tutorial to remove those optional columns.

**Review by rly — APPROVED** [review]

**Pull request merged**
