### PR TITLE
Propose logo for PyNWB

### PR DESCRIPTION
**Pull request by oruebel**
## Motivation

I was working on logos, so I figured I'd give it a shot to make a logo for PyNWB. What do you think?

## Checklist

- [ ] Did you update CHANGELOG.md with your changes?
- [X] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured the PR clearly describes the problem and the solution?
- [X] Is your contribution compliant with our coding style? This can be checked running `flake8` from the source directory.
- [X] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [X] Have you included the relevant issue number using "Fix #XXX" notation where XXX is the issue number? By including "Fix #XXX" you allow GitHub to close issue #XXX when the PR is merged.

### CODE REVIEW

**Comment by rly** [comment]
I like it!

Looks like one of the gallery tutorials references `logo.png`. This will have to be updated.

**Review by bendichter — DISMISSED** [review]
very cool!

**Comment by oruebel** [comment]
> Looks like one of the gallery tutorials references `logo.png`. This will have to be updated.

Thanks for pointing me to the error. This is fixed now. 

I'm glad that we are running the galleries as part of the CI. When building the docs on my laptop this error did not get triggered because sphinx gallery does not seem to run that tutorial when building the docs, probably because it doesn't have the plot prefix to indicate that we want to capture the output of code cells for this particular tutorial. This error is fixed now.

**Comment by oruebel** [comment]
@rly can you please reapprove

**Review by rly — APPROVED** [review]

**Pull request merged**
