### PR TITLE
Directly assess integration test container coverage

### LINKED ISSUE #320: Directly assessing integration test coverage
Currently, the scheme for reporting integration test coverage (i.e. which containers were run) relies on a decorator applied to the test case, which registers the tested class into a global variable. This variable is inspected by test.py and used to generate a report of the containers which are missing integration tests.

This scheme does not have a way to distinguish complete from incomplete test cases and also relies on the decorator being up-to-date with the test case's code.

To see this issue, simply run:
`python test.py -iv`

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?

### PR DESCRIPTION
**Pull request by NileGraddis**
Resolves #320

In this change, I use the result object returned by the test runner to find all of the failed or successful integration test cases, then obtain from those the tested container classes. Comparing this list to the typemap reveals which container classes were not tested.

To test, simply run `test.py -iv`

## Checklist

- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR description clearly describes problem and the solution?
- [x] Is your contribution compliant with our coding style ? This can be checked running `flake8` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [x] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ?

### CODE REVIEW

**Review by nicain — DISMISSED** [review]
LGTM; @ajtritt can you merge?

**Review by nicain — DISMISSED** [review]

**Review by ajtritt — APPROVED** [review]

**Review by ajtritt — CHANGES_REQUESTED** [review]
Python 3.6 looks good, but Python 2.7 and 3.5 are not reporting correctly

**Comment by NileGraddis** [comment]
@ajtritt hmm, I'm seeing the same behavior in 2.7/3.5/3.6 on my local machine. What is the issue that you are encountering? 

To run this, I am doing
```
source activate <an_env>
pip install -r requirements.txt -r requirements-dev.txt -r requirements-doc.txt
python setup.py develop
python test.py -iv
```

**Comment by NileGraddis** [comment]
@ajtritt I believe that I've resolved the issue that you noticed. The problem had to do with unordered dict iteration in TypeMap.merge - this worked in 3.6 only due the [accidental ordering of dictionaries](https://mail.python.org/pipermail/python-dev/2016-September/146327.html). Due to the lack of ordering, containers were being assigned to the wrong namespace (leaving core with only one class).

**Review by nicain — APPROVED** [review]
Nice Nile!

**Review by ajtritt — APPROVED** [review]

**Pull request merged**
