### PR TITLE
add py37

### PR DESCRIPTION
**Pull request by bendichter**
## Motivation

Test python 37 support

## How to test the behavior?
```
Show here how to reproduce the new behavior (can be a bug fix or a new feature)
```

## Checklist

- [ ] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [ ] Have you ensured the PR description clearly describes problem and the solution?
- [ ] Is your contribution compliant with our coding style ? This can be checked running `flake8` from the source directory.
- [ ] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [ ] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ?

### CODE REVIEW

**Comment by t-b** [comment]
@bendichter Should we add py37 support to circle CI as well?

**Comment by bendichter** [comment]
I'm not actually sure how to add a python version to CI. I was just
experimenting and I don't think my changes had the desired effect. But
yeah, if it passes let's cover it properly.

**Comment by dorukozturk** [comment]
@bendichter Sorry I did not see this PR and created a new one doing the same thing. I am working on adding 3.7 to CI now.

**Comment by bendichter** [comment]
Yeah that's fine.

**Pull request closed without merging**
