### PR TITLE
Load namespaces by default except in write mode and during validation

### LINKED ISSUE #1169: Set load_namespaces = True by default?
Should we set load_namespaces = True by default for `NWBHDF5IO`? I don't see why you would not want to load the cached specs that are usually necessary to read the file, but maybe I am not thinking of a use case.

### PR DESCRIPTION
**Pull request by rly**
Fix #1169.

### CODE REVIEW

**Review by t-b — APPROVED** [review]

**Comment by t-b** [comment]
@rly I think the validation fails as we need to use `load_namespaces=True` in the validator when we validate against a spec from the NWB file.

**Review by t-b — CHANGES_REQUESTED** [review]
See https://github.com/NeurodataWithoutBorders/pynwb/pull/1196#issuecomment-626798896

**Comment by bendichter** [comment]
I think at this point this PR has so many merge conflicts we should just start over. Thoughts, @rly?

**Comment by bendichter** [comment]
@rly can this be closed?

**Comment by rly** [comment]
Addressed by #1748

**Pull request closed without merging**
