### PR TITLE
Add support for HDMF 2.3

### PR DESCRIPTION
**Pull request by rly**
## Motivation

HDMF 2.3 introduces a few changes. This PR addresses those changes and updates the requirements to require hdmf >= 2.3.

## Checklist

- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR description clearly describes problem and the solution?
- [x] Is your contribution compliant with our coding style? This can be checked running `flake8` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [x] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number?

### CODE REVIEW

**Review by oruebel — APPROVED** [review]

**Review by bendichter — APPROVED** [review]

**Comment by bendichter** [comment]
@rly this also add support for 3.0?

**Comment by ajtritt** [comment]
> @rly this also add support for 3.0?

No, h5py 3.x support is not complete. It will likely be non-backward compatible

**Comment by bendichter** [comment]
@ajtritt ok. I'm trying to test out [hdmf enh/h5py 3.x](https://github.com/hdmf-dev/hdmf/pull/480) with pynwb and nwbwidgets. Would I have to take those changes and apply them to hdmf 2.3? Then use this branch of pynwb (or dev once it's merged)?

**Comment by bendichter** [comment]
It appears I got confused between the different packages. I thought there was an HDMF 3.0, but I was probably confusing that with the h5py 3.0 support.

**Comment by rly** [comment]
We were initially planning to release HDMF as version 3.0 but the breaking changes were not so important and support for h5py 3.x would be another breaking change, so we decided to pull the breaking changes out of the just-released release (2.3) and save them for an upcoming release that supports h5py 3.x.

**Comment by bendichter** [comment]
> We were initially planning to release HDMF as version 3.0 but the breaking changes were not so important and support for h5py 3.x would be another breaking change, so we decided to pull the breaking changes out of the just-released release (2.3) and save them for an upcoming release that supports h5py 3.x.

Thanks, this makes perfect sense and clarifies my confusion.

**Pull request merged**
