### PR TITLE
rc/2.0.0

### PR DESCRIPTION
**Pull request by rly**
This branch/PR tracks breaking changes to be released in PyNWB 2.0.0.

Guidelines:
- Merge PRs with breaking changes into this branch.
- Periodically merge updates from dev into this branch and make fixes as necessary.
- Otherwise avoid modifying this branch directly.
- This PR may involve changes to tens of files, and because each commit has been individually approved, this PR need not be reviewed with a close eye.
- When ready to release these changes:
  - merge dev into this branch
  - make fixes as necessary
  - rebase this branch
  - merge this branch into dev
  - delete this branch
- After all CI tests in dev pass, and before any minor/patch releases are cut, cut a major release from dev.

This workflow modifies the simple GitHub Flow workflow to handle the bundling of breaking changes into a major release without disrupting minor/patch releases out of the main development branch.

### CODE REVIEW

**Comment by rly** [comment]
Here are the remaining issues to address / PRs to merge for PyNWB 2.0.0 and nwb-schema 2.4.0. Happy to discuss removing/adding items.

PyNWB changes left to do (2.0.0):

- [x] Add/icephys meta
https://github.com/NeurodataWithoutBorders/pynwb/pull/1349

- [x] Add icephys functions to interact with pandas
https://github.com/NeurodataWithoutBorders/pynwb/pull/1383

- [x] Copy infrastructure changes from HDMF to PyNWB
(confirm that this has already been done in rc/2.0.0)
https://github.com/NeurodataWithoutBorders/pynwb/issues/1324 

- [x] CompassDirection.spatialSeries.data.unit problem
https://github.com/NeurodataWithoutBorders/pynwb/issues/1315
https://github.com/NeurodataWithoutBorders/pynwb/pull/1316

- [ ] TimeSeries can be written without 'data' dataset
https://github.com/NeurodataWithoutBorders/pynwb/issues/1220
https://github.com/NeurodataWithoutBorders/pynwb/pull/1274

- [x] Release HDMF 3.1.0 and use it in PyNWB

Schema changes (NWB 2.4.0):

- [ ] Make data required for ImageSeries, update docs
https://github.com/NeurodataWithoutBorders/nwb-schema/pull/462
  - [ ] Associated pynwb changes

- [ ] Change dtype of IndexSeries.data to uint32, update .data attributes
https://github.com/NeurodataWithoutBorders/nwb-schema/pull/459
  - [ ] Associated pynwb changes

- [ ] Define ElectrodesTable and FrequencyBandsTable types
https://github.com/NeurodataWithoutBorders/nwb-schema/pull/337
  - [ ] Associated pynwb changes

**Comment by oruebel** [comment]
@rly just an update on the icephys PRs:

- On the HDMF side we also need https://github.com/hdmf-dev/hdmf/pull/645 as #1383 depends on this.  https://github.com/hdmf-dev/hdmf/pull/645  is good to merge. 
- #1383 should be good to merge with #1349 soon. The PR is essentially complete. I just want to add a couple of extra tests and wanted to see if I can address a few more things, but nothing that would be critical or that could not be dealt with in separate PRs (even after the release if necessary)
     - Gallery tests are currently failing for this PR as the PR needs https://github.com/hdmf-dev/hdmf/pull/645. Once that has been merged the tests should all pass.
- #1349 is done and is only waiting for #1383 just so we have all in one PR. 
     - There is test failure for gallery38 here, but it looks like this is related to allen brain obervatory, so  this should be unrelated to the changes in the PR  https://app.circleci.com/pipelines/github/NeurodataWithoutBorders/pynwb/2003/workflows/ad3bbc18-5705-4da3-a7fa-1fdc35d2d256/jobs/41029

**Comment by rly** [comment]
I have painstakingly rebased this PR from 120+ commits down to 8 because I would like to merge this without squashing the individual commits. I double checked that the changes after rebase are the same as before the rebase. 

This is now ready to go. The individual changes have previously been reviewed and need not be carefully inspected.

**Comment by oruebel** [comment]
Great job @rly Thanks for all the hard work on this!

**Review by oruebel — APPROVED** [review]

**Pull request merged**
