### PR TITLE
Subject age timedelta

### LINKED ISSUE #1554: [Feature]: subject.age should accept a timedelta object
### What would you like to see added to PyNWB?

subject.age should accept a timedelta object

### Is your feature request related to a problem?

_No response_

### What solution would you like?

subject.age should accept a timedelta object

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

### PR DESCRIPTION
**Pull request by bendichter**
## Motivation

fix #1554 

## How to test the behavior?

```python
subject = Subject(subject_id='RAT123', age=timedelta(seconds=99999))
```

## Checklist

- [x] Did you update CHANGELOG.md with your changes?
- [ ] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [ ] Have you ensured the PR clearly describes the problem and the solution?
- [ ] Is your contribution compliant with our coding style? This can be checked running `flake8` from the source directory.
- [ ] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [ ] Have you included the relevant issue number using "Fix #XXX" notation where XXX is the issue number? By including "Fix #XXX" you allow GitHub to close issue #XXX when the PR is merged.

### CODE REVIEW

**Comment by rly** [comment]
I hesitate to ~homebrew~ ship our own solution for a timedelta -> ISO 8601 duration conversion, but this seems to be the best available and doesn't require adding a dependency.

**Comment by CodyCBakerPhD** [comment]
> I hesitate to ~homebrew~ ship our own solution for a timedelta -> ISO 8601 duration conversion, but this seems to be the best available and doesn't require adding a dependency.

PyNWB requires `pandas`: https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/setup.py#L25

`pandas` has a `Timedelta` to ISO functioanlity we would want:

```python
from pandas import Timedelta

time_delta = Timedelta(days=2,weeks=1, minutes=50, seconds=12)
iso_string = time_delta.isoformat()
```

so all you would have to do to accommodate both that class type and `datetime.timedelta` is map a `datetime.timedelta` onto the `pandas.Timedelta` and it's out of our hands and safely the responsibility of upstream dependencies.

**Comment by CodyCBakerPhD** [comment]
And actually, as far as I can tell, `pandas.Timedelta` can take `datetime.timedelta` objects as the input.

```python
import datetime
import pandas

time_delta = pandas.Timedelta(datetime.timedelta(days=2,weeks=1, minutes=50, seconds=12))
iso_string = time_delta.isoformat()
```

**Comment by bendichter** [comment]
I think this is a pretty simple function and I'm pretty confident it's going to work but I'd also be fine with using pandas

**Review by rly — APPROVED** [review]

**Comment by rly** [comment]
Looks good to me. Thanks!

**Pull request merged**
