### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by rly**

### CODE REVIEW

**Comment by bendichter** [comment]
So this would officially drop py2 for CI? (#933) I was thinking we could wait until the official EOL, Jan 1 2020. It would be nice to have py3 features sooner though. Is there anyone who really needs py2 support?

**Comment by rly** [comment]
My mistake. We should continue to test with python 2.7 until we officially drop support. I'll change it

**Comment by rly** [comment]
Currently, we have CircleCI for tests on Linux (basic python - 4 versions, miniconda - 4 versions, gallery - 4 versions, flake8), we have Travis for tests on Mac OS (basic python - 4 versions), and we have Appveyor for tests on Windows (basic python - 3 versions). 

@jcfr and I discussed doing the Windows and Mac OS basic python tests in Azure instead of Travis and Appveyor. We would still run the full test suite for Linux on CircleCI because those tests might be faster on CircleCI rather than having everything in a single Azure pipeline. It may be, however, that it is totally fine to put everything in Azure. 

Any thoughts?

**Comment by rly** [comment]
@jcfr I think this is good to merge. I don't have access to the Appveyor account. Can you disable the CI there? I believe I have it now disabled on Travis.

**Review by ajtritt — APPROVED** [review]

**Comment by jcfr** [comment]
>  I don't have access to the Appveyor account. Can you disable the CI there?

I just invited you so that you also have admin right on the AppVeyor account. This should allow you to preform the required updates.

Suggested step:

* update the setting of the repo to remove AppVeyor as a required CI
* remove https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/appveyor.yml ?
* remove appveyor as an app on the project ?

**Comment by rly** [comment]
Thanks @jcfr !

I have:
- updated the setting of the repo to remove AppVeyor as a required CI, and I added Azure for Windows 3.7 as a required CI
- disabled appveyor and travis webhooks on the repo
- removed the appveyor.yml and travis yml files

I did not delete the pynwb project from the Appveyor account. I also did not delete the pynwb project from the Travis account. They will just be inactive unless someone wants to remove them for good.

**Pull request merged**
