### PR TITLE
Release 2.5.0/ Update ExternalResources to HERD

### PR DESCRIPTION
**Pull request by mavaylon1**
Prepare for release of PyNWB [2.5.0]

### Before merging:
- [x] Major and minor releases: Update package versions in `requirements.txt`, `requirements-dev.txt`,
  `requirements-doc.txt`, `requirements-min.txt`, `environment-ros3.yml`, and `setup.py` as needed.
- [x] Check legal file dates and information in `Legal.txt`, `license.txt`, `README.rst`, `docs/source/conf.py`,
  and any other locations as needed
- [x] Update `setup.py` as needed
- [x] Update `README.rst` as needed
- [x] Update `src/pynwb/nwb-schema` submodule as needed. Check the version number and commit SHA manually
- [x] Update changelog (set release date) in `CHANGELOG.md` and any other docs as needed
- [x] Run tests locally including gallery, validation, and streaming tests, and inspect all warnings and outputs
  (`python test.py -v -p -i -b -w -r > out.txt 2>&1`)
- [x] Test docs locally (`make clean`, `make html`)
- [x] Push changes to this PR and make sure all PRs to be included in this release have been merged
- [x] Check that the readthedocs build for this PR succeeds (build latest to pull the new branch, then activate and
  build docs for new branch): https://readthedocs.org/projects/pynwb/builds/
## Motivation

What was the reasoning behind this change? Please explain the changes briefly.
This is to update pynwb with the name update for ExternalResources in HDMF and hdmf-common-schema.

## How to test the behavior?
```
Show how to reproduce the new behavior (can be a bug fix or a new feature)
```
Run the unit tests

## Checklist

- [x] Did you update CHANGELOG.md with your changes?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR clearly describes the problem and the solution?
- [x] Is your contribution compliant with our coding style? This can be checked running `flake8` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [x] Have you included the relevant issue number using "Fix #XXX" notation where XXX is the issue number? By including "Fix #XXX" you allow GitHub to close issue #XXX when the PR is merged.

### CODE REVIEW

**Comment by mavaylon1** [comment]
@oruebel Should we do a minor release for HDMF for this PR or wait till the first stage of Termset is done and merged.

**Comment by bendichter** [comment]
Could we move this along? Having the dev branches out of sync between HDMF and PyNWB makes it difficult to develop new features. In the future, would it be possible to prepare these branches at the same time and merge them at more or less the same time?

**Comment by mavaylon1** [comment]
> Could we move this along? Having the dev branches out of sync between HDMF and PyNWB makes it difficult to develop new features. In the future, would it be possible to prepare these branches at the same time and merge them together?

The plan is to do a release this week. It took time to get a review for certain merges in HDMF. My hope is that all the merges can get in today on the HDMF side so I can do a release. Then tomorrow I'll do a fix on the hdmf version here.

**Comment by oruebel** [comment]
> would it be possible to prepare these branches at the same time and merge them at more or less the same time?

Getting things to match exactly is tricky, but I agree, we'll try to merge these kind of interdependent PRs in a closer order in the future. This one was in part my fault for being to quick with approvals.

**Review by rly — APPROVED** [review]

**Pull request merged**
