### PR TITLE
Change dtype of imaging_rate from str to float

### LINKED ISSUE #136: Change `ophys.ImagingPlane` fields `excitation_lambda` and `imaging_rate` from `str` to `float`
https://github.com/NeurodataWithoutBorders/nwb-schema/blob/a0042022f7cf1dc0c7a6a17bbfa17fc5c5e41824/core/nwb.ophys.yaml#L197

Is there a reason why these are stored as strings? It seems more sensible to store them as floats.

### PR DESCRIPTION
**Pull request by oruebel**
## Motivation

Change dtype of ImagingPlane.imaging_rate from str to float

* Fix https://github.com/NeurodataWithoutBorders/nwb-schema/issues/136
* Replace https://github.com/NeurodataWithoutBorders/nwb-schema/pull/155 and complete missing updates to the ImagingPlane container class and related tests in PyNWB
* Implement changes from https://github.com/NeurodataWithoutBorders/nwb-schema/pull/154 in PyNWB so they can be merged over with the changed schema
* Implement spelling fixes from https://github.com/NeurodataWithoutBorders/nwb-schema/pull/138 in PyNWB so they can be merged over with the changed schema

## Checklist

- [X] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured the PR description clearly describes problem and the solution?
- [X] Is your contribution compliant with our coding style ? This can be checked running `flake8` from the source directory.
- [X] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change? -- This PR supersedes previous PRs.
- [X] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ?

### CODE REVIEW

**Comment by oruebel** [comment]
@ajtritt this PR is port over and close out some of the pending PRs on the nwb-schema repo that have not made it over here. I've already closed the corresponding PRs on the schema repo to make sure that I don't forget to do it later.

**Comment by bendichter** [comment]
The CI of #615 relies on this

**Comment by bendichter** [comment]
@nicain looks like CircleCI is having issues with the Allen servers:

2018-09-13 00:15:52,314 - DEBUG - http://api.brain-map.org:80 "GET /api/v2/well_known_file_download/562217752 HTTP/1.1" 200 464249037
Too long with no output (exceeded 10m0s)

Do you know anything about this?

**Review by ajtritt — APPROVED** [review]
Looks fine to me. Please merge if tests pass

**Pull request closed without merging**
