### PR TITLE
rmv py3.7

### LINKED ISSUE #1712: Drop 3.7?
### What happened?

Python 3.7 on macs is failing CI. Something to do with compiling compression algorithms. Python 3.7 officially drops support in 3 days, so I vote we just remove support for 3.7 and don't worry about fixing it.

### Steps to Reproduce
See CI: https://github.com/NeurodataWithoutBorders/pynwb/actions/runs/5384927945/jobs/9773407167?pr=1707

### Traceback

_No response_

### Operating System

macOS

### Python Executable

Python

### Python Version

3.7

### Package Versions

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

### PR DESCRIPTION
**Pull request by bendichter**
## Motivation

fix #1712

### CODE REVIEW

**Comment by mavaylon1** [comment]
@rly @oruebel can this be merged? I need this in order to merge the ER updates since hdmf dropped python 3.7.

**Review by mavaylon1 — DISMISSED** [review]

**Comment by mavaylon1** [comment]
@rly could you also updated the issue template to remove the python 3.7 option in the drop down menu?

**Comment by mavaylon1** [comment]
We can ignore the link issue. I generated a ticket and will fix it today. #1719

**Comment by rly** [comment]
> @rly could you also updated the issue template to remove the python 3.7 option in the drop down menu?

Already done in this PR

**Review by rly — APPROVED** [review]

**Pull request merged**
