### PR TITLE
Enh/epoch refactor

### PR DESCRIPTION
**Pull request by ajtritt**
## Motivation

Epochs were being stored inefficiently

## How to test the behavior?
``` python
from pynwb import NWBFile 
from pynwb.ecephys import 
from pynwb.behavior import SpatialSeries

f = NWBFile(...)
ephys_ts = ElectricalSeries(...)
f.add_acquisition(ephys_ts)

spatial_ts = SpatialSeries(...)
f.add_acquisition(spatial_ts)

f.create_epoch(name='epoch1', start_time=0.0, stop_time=1.0, tags=epoch_tags,
               description="the first test epoch", timeseries=[ephys_ts, spatial_ts])

f.create_epoch(name='epoch2', start_time=0.0, stop_time=1.0, tags=epoch_tags,
               description="the second test epoch", timeseries=[ephys_ts, spatial_ts])
```

## Checklist

- [ ] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [ ] Have you ensured the PR description clearly describes problem and the solution?
- [ ] Is your contribution compliant with our coding style ? This can be checked running `flake8` from the source directory.
- [ ] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [ ] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ?

### CODE REVIEW

**Comment by neuromusic** [comment]
so if I have 4000 epochs, I need to define a source and description for each and every one?

**Comment by oruebel** [comment]
@neuromusic I'm glad your are reviewing these changes. Instead of taking a critical approach to comments and feedback:

> so if I have 4000 epochs, I need to define a source and description for each and every one?

I'd appreciate it if you could try to formulate these kind of question in a more inclusive and constructive fashion. E.g., you could say something like: "Thanks for this change. Do I understand this structure correctly that every Epoch requires a separate source and description? In cases where users need to create large numbers of Epochs I think this could be problematic. Do you have any suggestions on how to address this potential problem?" We are all working very hard on this and constructive feedback is always better than criticism. Thanks again for all your efforts on this project!

**Comment by ajtritt** [comment]
@neuromusic For _source_, no--this is a typo. For _description_, yes--if you are going to set 4000 start/stop times, you need to differentiate them and provide information about what's starting/stopping. 

If you are trying to store trial data, then epochs alone is probably the wrong solution.

**Review by oruebel — DISMISSED** [review]

**Review by oruebel — DISMISSED** [review]
Thanks for the additional fix. Looks good.

**Comment by ajtritt** [comment]
@neuromusic I added a type called "EventTable" that has three columns: _start_time_, _stop_time_, and _tags_ (_tags_ is just a string of tags). The PyNWB class is in pynwb.epochs.EpochTable. You can extend this for your needs.

**Comment by bendichter** [comment]
@ajtritt I'm having a bit of trouble incorporating this into my conversion script. Previously, I was able to link a single epoch to multiple timeseries objects at once. Now, when I add a row, the `timeseries` argument expects a `RegionSlicer` object, and throws an error when I try to use a list of `TimeSeries` objects.

**Comment by bendichter** [comment]
or am I supposed to use `pynwb.epoch.Epochs.add_epoch`

**Pull request merged**
