### PR TITLE
Install tox with conda

### LINKED ISSUE #591: miniconda36 build error: cannot find setuptools
error:

```
FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg
```

[link](https://circleci.com/gh/NeurodataWithoutBorders/pynwb/7139?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

### PR DESCRIPTION
**Pull request by dorukozturk**
See https://github.com/ContinuumIO/anaconda-issues/issues/542

## Motivation

Fixes #591

### CODE REVIEW

**Comment by bendichter** [comment]
@dorukozturk thanks for looking into this. The minicondas are still failing:

```
py36 create: /root/project/.tox/py36
ERROR: invocation failed (exit code 100), logfile: /root/project/.tox/py36/log/py36-0.log
ERROR: actionid: py36
msg: getenv
cmdargs: ['/opt/conda/bin/python', '-m', 'virtualenv', '--python', '/opt/conda/bin/python3.6', 'py36']

/root/project/.tox/py36/bin/python3.6: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
Using base prefix '/opt/conda'
New python executable in /root/project/.tox/py36/bin/python3.6
Also creating executable in /root/project/.tox/py36/bin/python
ERROR: The executable /root/project/.tox/py36/bin/python3.6 is not functioning
ERROR: It thinks sys.prefix is '/root/project/.tox' (should be '/root/project/.tox/py36')
ERROR: virtualenv is not compatible with this system or executable
Running virtualenv with interpreter /opt/conda/bin/python3.6

ERROR: Error creating virtualenv. Note that some special characters (e.g. ':' and unicode symbols) in paths are not supported by virtualenv. Error details: InvocationError('/opt/conda/bin/python -m virtualenv --python /opt/conda/bin/python3.6 py36 (see /root/project/.tox/py36/log/py36-0.log)', 100)
___________________________________ summary ____________________________________
ERROR:   py36: Error creating virtualenv. Note that some special characters (e.g. ':' and unicode symbols) in paths are not supported by virtualenv. Error details: InvocationError('/opt/conda/bin/python -m virtualenv --python /opt/conda/bin/python3.6 py36 (see /root/project/.tox/py36/log/py36-0.log)', 100)
Exited with code 1
```

**Comment by dorukozturk** [comment]
@bendichter I am trying to solve that. It is an interesting one :)

**Comment by dorukozturk** [comment]
@bendichter can you take a look?

**Review by bendichter — APPROVED** [review]

**Comment by bendichter** [comment]
@dorukozturk Looks good! I'm glad you were able to find a simple solution.

**Pull request merged**
