### PR TITLE
Fix codecov

### LINKED ISSUE #304: CodeCov not pulling in all code
## 1) Bug

Looking at the most recent build, some of the PyNWB modules are missing from the tested source.
The following source files are missing from src/pynwb and src/pynwb/io (except spec.py)
- base.py
- behavior.py
- core.py
- ecephys.py
- epoch.py
- file.py
- icephys.py
- image.py
- misc.py 
- ogen.py
- ophys.py
- retinotopy.py
- spec.py (only src/pynwb)

## Checklist

- [ ] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [ ] Have you included a brief and descriptive title?
- [ ] Have you included a clear description of the problem you are trying to solve?
- [ ] Have you included a minimal code snippet that reproduces the issue you are encountering?

### PR DESCRIPTION
**Pull request by dorukozturk**
Fixes #304

### CODE REVIEW

**Comment by ajtritt** [comment]
looking better, but it's still missing some files:
e.g. https://codecov.io/gh/NeurodataWithoutBorders/pynwb/pull/322/tree/src/pynwb/io
This only has 
__init__.py
base.py
core.py
ecephys.py
epoch.py
file.py
ophys.py

It should have the following:
__init__.py
base.py
behavior.py
core.py
ecephys.py
epoch.py
file.py
icephys.py
image.py
misc.py
ogen.py
ophys.py
retinotopy.py

**Comment by ajtritt** [comment]
The missing files are empty. CodeCov must ignore them since there's nothing to cover?

**Comment by dorukozturk** [comment]
@ajtritt Yes, that is the case(your commit added the icephys.py to codecov https://codecov.io/gh/NeurodataWithoutBorders/pynwb/tree/40853afc84c95ff68b8b665e3ef4d2680dc650be/src/pynwb/io) and I think it is the right behavior. Can I merge it after I revert your commit then?

**Review by ajtritt — DISMISSED** [review]

**Comment by ajtritt** [comment]
@dorukozturk Yes, you can revert my change and merge.

**Pull request merged**
