### PR TITLE
make Image basetype a dataset

### PR DESCRIPTION
**Pull request by ajtritt**
## Motivation

make Image base type a dataset

## Checklist

- [ ] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [ ] Have you ensured the PR description clearly describes problem and the solution?
- [ ] Is your contribution compliant with our coding style ? This can be checked running `flake8` from the source directory.
- [ ] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [ ] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ?

### CODE REVIEW

**Comment by bendichter** [comment]
@ajtritt I like this if we can make it work but right now there's an error:
`TypeError: incorrect type for 'neurodata_type_inc' (got 'NWBDatasetSpec', expected 'NWBGroupSpec or str')`

**Comment by bendichter** [comment]
@ajtritt 

Can datasets have datasets? Or should it be:

```yaml
datasets:
- neurodata_type_def: GrayscaleImage
  neurodata_type_inc: Image
  doc: Grayscale image. Origin in top left.
  shape:
    - null
    - null
  dims:
    - 'y'
    - 'x'
- neurodata_type_def: RGBImage
  neurodata_type_inc: Image
  doc: Color image. Origin in top left.
  shape:
  - null
  - null
  - 3
  dims:
  - 'y'
  - 'x'
  - 'R,G,B'
- neurodata_type_def: RGBAImage
  neurodata_type_inc: Image
  doc: Color image with transparency. Origin in top left.
  shape:
  - null
  - null
  - 4
  dims:
  - 'y'
  - 'x'
  - 'R,G,B,A'
```

**Comment by ajtritt** [comment]
@bendichter yes, you are correct. I sloppily copy-pasted... I just changed it though.

**Comment by bendichter** [comment]
@ajtritt How do you interact with these types of datasets in `pynwb`? I don't see any such datasets in any of the schema namespace files other than abstract types in `base`

**Comment by ajtritt** [comment]
@bendichter there is an Image base class in file.py

https://github.com/NeurodataWithoutBorders/pynwb/blob/b9a2ef1a7125607edc05f66859cc29f843aa4702/src/pynwb/file.py#L26

It’s not fully implemented right now, but it would just need to be implemented to support the necessary attributes on the dataset, and the necessary subclasses would need to be added.

**Comment by bendichter** [comment]
why specify `Image` in `nwb.base.yaml` and then define the constructor in `file.py`? Wouldn't it make more sense to have the constructor in `base.py`?

**Comment by ajtritt** [comment]
Sure, it probably makes more sense. But, there's no requirement about where specs are and where their API classes are.

**Pull request merged**
