### PR TITLE
CI Enhancements

### PR DESCRIPTION
**Pull request by dorukozturk**
This PR enhances the CI aspect of pynwb.
Here are the keys component of this PR:

1) Added tox to reduce the complexity of running tests on multiple python versions.
2) Added Appveyor as the primary Windows test runner.
3) Added Circleci as the primary Linux test runner.
4) Configured Travis to be the primary Osx test runner.
5) Added placeholder badges for different CI providers. (We will need to replace the urls with the real ones. Currently they are pointing to a fork that I created)
6) Fixed some minor issues on closing test/temporary files.

### CODE REVIEW

**Comment by dorukozturk** [comment]
@ajtritt or @oruebel Can one of you activate Circleci and Appveyor for this repo?

**Comment by jcfr** [comment]
xref #120

**Review by ajtritt — DISMISSED** [review]
Looks good to me, thanks for doing this.

**Comment by oruebel** [comment]
I'm working on creating the AppVeyor accounts, i.e.,  #120 right now

**Review by nicain — DISMISSED** [review]
Looks all good to me!

**Comment by oruebel** [comment]
@dorukozturk  quick question regarding the following change:

```
     def setUp(self):
-        self.test_temp_file = tempfile.NamedTemporaryFile()
-        self.f = h5py.File(self.test_temp_file.name, 'w')
+        self.test_temp_file = tempfile.NamedTemporaryFile(delete=True)
+        name = self.test_temp_file.name
+        self.test_temp_file.close()
+        self.f = h5py.File(name, 'w')

```

If I remember the behavior of NamedTemporaryFile correctly the file will be deleted automatically once ```self.test_temp_file.close() ``` gets called. This means that now ```self.f = h5py.File(name, 'w')``` should actually create a new file with the same name as the temporary file, rather than actually using the file that was created by NamedTemporaryFile. If this is the case, then I believe the file that is being created may not get deleted properly once the tests are done. I have not tested this, so I might be wrong, but I think removing ```self.test_temp_file.close()``` or adding an explicit rm of the file to the tearDown would fix this.

**Comment by jcfr** [comment]
>  the behavior of NamedTemporaryFile correctly the file will be deleted

That is correct, I wonder with the issue was related to python 14243 (see [here](https://github.com/scikit-build/scikit-ci/blob/9cae36620eddafec41d611c52a490e098cf7b7fa/ci/driver.py#L165-L166) for details)

Either way, if this workarounds a particular problem, a comment should be added.

**Comment by oruebel** [comment]
@jcfr I'm not sure. The link seems to suggest to set```delete=False``` on NamedTemoraryFile. However in the code here sets```delete=True```. Either way,  since the temp file is being closed in the setUp function, I believe we need to explicitly delete the created file in the tearDown function. It's fine if this is needed to work around another problem, however, we should make sure that the file is being deleted when the tests are done. If it is a workaround, then it would be also be good to add a quick comment to the code as well  just so we don't accidentally unfix the fix later.

**Comment by jcfr** [comment]
> we need to explicitly delete the created file in the tearDown function.

:+1:

**Comment by dorukozturk** [comment]
@oruebel According to h5py.File documentation [here](http://docs.h5py.org/en/latest/high/file.html), if the file exists, in the write mode it will try to truncate. On Windows though if that file is open, operating system won't let h5py to delete and recreate that file. It was raising an error on my builds. It was not executing the tests, thus tearDown method was not getting called at all. I had to solve that problem on the setUp phase. Because once we created the file and it was open by the Python process, the OS was blocking anything else to delete that file. My workaround was using NamedTempFile as a temporary path generator, get the flie path it creates, dump the file and let h5py recreate a fresh file with the path generated by NamedTempFile. I must have forget to delete that kwarg (delete=True) which is unnecessary. It is the default behavior anyways. I will delete it. I hope that clarifies. 

Also @oruebel you are right, we should delete the files in the tearDown. I will add that when I have the chance.

**Comment by jcfr** [comment]
@dorukozturk  AppVeyor is now available: https://ci.appveyor.com/project/NeurodataWithoutBorders/pynwb

**Comment by jcfr** [comment]
@oruebel  To setup CircleCI, look like you need to either add the project or grant one of us with admin access to do so.

circleci-pywnb-admin-required-to-add

**Comment by oruebel** [comment]
@dorukozturk thanks for the clarification on the reason for the change. That makes sense. Can you update the tearDown function to delete the file. Essentially what I believe is missing is:

```
import os
os.remove(f.filename)
```
Also, could you add a quick comment to the setUp() function with the reason why we need to close the NamedTemporaryFile.

**Comment by dorukozturk** [comment]
@oruebel I activated Circleci, thus this is ready for the final review.

**Comment by jcfr** [comment]
Well done 👍 

@dorukozturk Look like the CircleCI and Appveyor build associated haven't been submitted 
* https://ci.appveyor.com/project/NeurodataWithoutBorders/pynwb/history
* https://circleci.com/gh/NeurodataWithoutBorders/pynwb

May be you could update the last commit of the PR and force push to re-trigger them ...

Here are the status from PR #122 I could retrieve:
* TravisCI: https://travis-ci.org/NeurodataWithoutBorders/pynwb/builds/280139880

**Pull request merged**
