### PR TITLE
make IntervalSeries write NaN. fix #592

### LINKED ISSUE #592: IntervalSeries.data.conversion is stored as 'NaN'
IntervalSeries.conversion returns `conversion = 1.0` before and after read:

```python
from pynwb import NWBFile, NWBHDF5IO
from pynwb.misc import IntervalSeries

interval_series = IntervalSeries(data=[-1, 1], timestamps=[1, 2], name='test_interval_series', source='source')

print(interval_series.conversion)

nwbfile = NWBFile("source", "a file with header data", "NB123A", '2018-06-01T00:00:00')
nwbfile.add_acquisition(interval_series)

with NWBHDF5IO('test_interval_series.nwb', 'w') as io:
    io.write(nwbfile)
    
with NWBHDF5IO('test_interval_series.nwb', 'r') as io:
    nwbfile_in = io.read(nwbfile)
    print(nwbfile_in.acquisition['test_interval_series'].conversion)
```

```
1.0
1.0
```

However the data is actually stored as `'NaN'` (the string `'NaN'`, not a NaN float value):
```python
import h5py
with h5py.File('test_interval_series.nwb', 'r') as file:
    print(file['acquisition']['test_interval_series']['data'].attrs['conversion'])
```
```
NaN
```

This is causing issues for matnwb, which expects this value to follow the schema, which defines it to be a float. Is there a reason why it's stored this way?

### PR DESCRIPTION
**Pull request by ajtritt**
## Motivation

fix #592 

## How to test the behavior?
```
from pynwb import NWBFile, NWBHDF5IO
from pynwb.misc import IntervalSeries

interval_series = IntervalSeries(data=[-1, 1], timestamps=[1, 2], name='test_interval_series', source='source')

print(interval_series.conversion)

nwbfile = NWBFile("source", "a file with header data", "NB123A", '2018-06-01T00:00:00')
nwbfile.add_acquisition(interval_series)

with NWBHDF5IO('test_interval_series.nwb', 'w') as io:
    io.write(nwbfile)

with NWBHDF5IO('test_interval_series.nwb', 'r') as io:
    nwbfile_in = io.read(nwbfile)
    print(nwbfile_in.acquisition['test_interval_series'].conversion)

import h5py
with h5py.File('test_interval_series.nwb', 'r') as file:
    print(file['acquisition']['test_interval_series']['data'].attrs['conversion'])
```

Should produce:

```
-1.0
-1.0
-1.0
```

## Checklist

- [ ] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [ ] Have you ensured the PR description clearly describes problem and the solution?
- [ ] Is your contribution compliant with our coding style ? This can be checked running `flake8` from the source directory.
- [ ] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [ ] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ?

### CODE REVIEW

**Review by bendichter — DISMISSED** [review]
ahh what an elegant solution. Good work!

**Review by oruebel — DISMISSED** [review]
I think at least for conversion the idea was to also change the default value to 1.0 but I think NaN is fine.


I believe with this we should close. https://github.com/NeurodataWithoutBorders/pynwb/pull/605

**Comment by bendichter** [comment]
I have a slight preference for resolution: NaN, conversion: 1.0, but both nans are ok. The important thing is that they are type double. Now do we know what circleci is complaining about?

**Comment by ajtritt** [comment]
doing away with NaN all together. NaN has weird behavior. Going with conversion=1.0, resolution=-1.0

**Review by bendichter — APPROVED** [review]

**Pull request merged**
