### PR TITLE
doc: Add module API documentation. See #267

### PR DESCRIPTION
**Pull request by jcfr**
## Motivation

API documentation missing from readthedocs. See #267 

Look like an alternative would be to write our builder on readthedocs, not sure if it is worth the effort. I think it is reasonable to expect developer to locally generated the documentation and checked in the update.

See https://docs.readthedocs.io/en/latest/builds.html#understanding-what-s-going-on

### CODE REVIEW

**Comment by oruebel** [comment]
@jcfr the apidoc should be run on read-the-docs directly. I believe that is how @ajtritt had set the PyNWB docs up originally and that is also how the schema-docs work. If the docs are not being generated then that should be a bug in ``docs/source/conf.py`` I can take a look later.

**Review by nicain — APPROVED** [review]

**Comment by oruebel** [comment]
@jcfr @nicain looking at the  ``conf.py`` it already has the ``run_apidoc(_)`` function to generate the apidocs as part of the build. I'll check why it is not being run.

**Comment by oruebel** [comment]
@jcfr @nicain @dorukozturk Ok, I found the problem. This issue is that in https://github.com/NeurodataWithoutBorders/pynwb/commit/39c9a711cefeaef84e76d4adcfaa754b84155f09  @dorukozturk added a ``setup`` function at the end of conf.py but the file already contained a ``setup`` function (line 124) to do the autogenerate of the souces and the new function simply overwrote the previous setup.py function. I'll fix the bug and submit a pull request soon. @jcfr as far as I can tell, this pull request only adds the autogenerated sphinx sources. As such I suggest we do not merge this pull request and I'll add the fix in the upcoming request.

**Comment by oruebel** [comment]
@jcfr @nicain @dorukozturk @ajtritt I just added #280 which should fix this problem.

**Comment by nicain** [comment]
Closed because #280 has resolved the original concern.

**Pull request closed without merging**
