### PR TITLE
make MotionCorrection test

### LINKED ISSUE #1373: MotionCorrection not working
The init requires arg named "`corrected_images_stacks`", but this is not correctly mapped on write:

```python
~/opt/anaconda3/lib/python3.7/site-packages/hdmf/utils.py in func_call(*args, **kwargs)
    578             def func_call(*args, **kwargs):
    579                 pargs = _check_args(args, kwargs)
--> 580                 return func(args[0], **pargs)
    581         else:
    582             def func_call(*args, **kwargs):

~/opt/anaconda3/lib/python3.7/site-packages/hdmf/build/objectmapper.py in get_attr_value(self, **kwargs)
    550                 msg = ("%s '%s' does not have attribute '%s' for mapping to spec: %s"
    551                        % (container.__class__.__name__, container.name, attr_name, spec))
--> 552                 raise ContainerConfigurationError(msg)
    553             if attr_val is not None:
    554                 attr_val = self.__convert_string(attr_val, spec)

ContainerConfigurationError: MotionCorrection 'MotionCorrection' does not have attribute 'corrected_image_stacks' for mapping to spec: {'doc': 'Reuslts from motion correction of an image stack.', 'quantity': '+', 'neurodata_type_inc': 'CorrectedImageStack'}
```

the arg name should be `corrected_image_stacks`

### PR DESCRIPTION
**Pull request by bendichter**
fix #1373 

Attempt to make MotionCorrection test. I don't understand why it's failing

### CODE REVIEW

**Comment by bendichter** [comment]
@rly please help?

**Comment by rly** [comment]
The root problem is that the schema says that the schema for `CorrectedImageStack` says that the name of the child `ImageSeries` has to be "corrected", but the API class for `CorrectedImageStack` allows any name for the child `ImageSeries`. I updated the PR to add a check for this. 

This feels clunky, like we should not have this gotcha when defining schema. I know Akshay ran into this with his extensions, where the names have to match in order for the data to be read and validated correctly. In some cases, it is better not to enforce a name on the container containing a child neurodata type, but names are helpful and some data types like `CorrectedImageStack` or let's say a type that contains two specific `TimeSeries` need to use the name to disambiguate.

**Comment by oruebel** [comment]
> The root problem is that the schema says that the schema for `CorrectedImageStack` says that the name of the child `ImageSeries` has to be "corrected", but the API class for `CorrectedImageStack` allows any name for the child `ImageSeries`. I updated the PR to add a check for this

I think the `required_name` approach is appropriate for this. Similar to how we warn on data-type changes we could here also fix the name on write to be compliant with the schema and issue a "InvaldiContainerName" warning.

**Comment by bendichter** [comment]
Thanks @rly ! This looks good to me!

**Review by rly — APPROVED** [review]

**Pull request merged**
