### PR TITLE
add cell_id to IntracellularElectrode

### PR DESCRIPTION
**Pull request by bendichter**
## Motivation

relies on https://github.com/NeurodataWithoutBorders/nwb-schema/pull/512

### CODE REVIEW

**Comment by rly** [comment]
Please add a roundtrip test, which will probably only work after the schema is updated.

**Comment by bendichter** [comment]
done. Should I update the nwb schema as well?

**Comment by rly** [comment]
Yes, please update the schema submodule to point to the head of nwb-schema.

**Review by rly — APPROVED** [review]

**Comment by rly** [comment]
@bendichter this is good to go

**Pull request merged**
