### PR TITLE
change imaging_rate to be optional

### PR DESCRIPTION
**Pull request by bendichter**
## Motivation

https://github.com/NeurodataWithoutBorders/nwb-schema/pull/429

### CODE REVIEW

**Comment by bendichter** [comment]
I had to switch to kwargs on a number of tests. Technically this breaks backwards compatibility for `ImagingPlane` if the user was using ordered args.

**Review by rly — APPROVED** [review]

**Comment by bendichter** [comment]
@rly do we also need to update the commit of nwb-schema?

**Comment by rly** [comment]
Yes, good point. I was going to update it in the schema_2.2.3 branch (where this would merge into) but it makes more sense to update the schema commit here. Could you do that? I'll approve after, and then you can merge it.

**Comment by bendichter** [comment]
I am not sure I know how..

**Comment by bendichter** [comment]
Also, I didn't realize this was going into another sub-branch. I thought it was going into dev. I'm OK with changing the nwb-schema commit there.

**Comment by rly** [comment]
From the pynwb project root, `cd src/pynwb/nwb-schema`. Then run `git pull origin dev`

**Pull request merged**
