### PR TITLE
add links and references to validator

### LINKED ISSUE #208: testing: Add test trying to run validate CLI
See https://github.com/NeurodataWithoutBorders/pynwb/pull/205#issuecomment-342605950

### LINKED ISSUE #698: Type promotion logic does not take into account the signedness for integer types
Build the `icephys.py` example in docs/gallery/domain.

Look into the nwb file with `h5dump icephys_example.nwb  | grep -C 10 conversion`:

```
          ATTRIBUTE "conversion" {
             DATATYPE  H5T_IEEE_F64LE
             DATASPACE  SCALAR
             DATA {
             (0): 1e-012
             }
          }
```

So the conversion attribute is stored as 64bit IEEE float little endian (aka double).
But the YAML file `nwb.base.yaml` says

```
    - name: conversion
      dtype: float32
      doc: Scalar to multiply each element in data to convert it to the specified
        unit
      default_value: 1.0
      required: false
```

So they both don't agree.

Where are the types in HDF5 decided? And from what data?

### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Python
- **Python Version:** Python 3.6
- **Operating System:** Windows
- **Pynwb Version:** dev branch form today

### LINKED ISSUE #715: Validator broken
Take one of the docs/gallery/general nwb files and call `python -m pynwb.validate basic_example.nwb` and you get

```
$ python -m pynwb.validate basic_example.nwb
C:\Anaconda2\envs\py36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to
 `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "C:\Anaconda2\envs\py36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda2\envs\py36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "e:\projekte\pynwb\src\pynwb\validate.py", line 58, in <module>
    main()
  File "e:\projekte\pynwb\src\pynwb\validate.py", line 52, in main
    errors = validate(io)
  File "e:\projekte\pynwb\src\pynwb\form\utils.py", line 390, in func_call
    return func(**parsed['args'])
  File "e:\projekte\pynwb\src\pynwb\__init__.py", line 186, in validate
    return validator.validate(builder)
  File "e:\projekte\pynwb\src\pynwb\form\utils.py", line 375, in func_call
    return func(self, **parsed['args'])
  File "e:\projekte\pynwb\src\pynwb\form\validate\validator.py", line 314, in validate
    return validator.validate(builder)
  File "e:\projekte\pynwb\src\pynwb\form\utils.py", line 375, in func_call
    return func(self, **parsed['args'])
  File "e:\projekte\pynwb\src\pynwb\form\validate\validator.py", line 391, in validate
    ret.extend(sub_val.validate(bldr))
  File "e:\projekte\pynwb\src\pynwb\form\utils.py", line 375, in func_call
    return func(self, **parsed['args'])
  File "e:\projekte\pynwb\src\pynwb\form\validate\validator.py", line 369, in validate
    ret = super(GroupValidator, self).validate(builder)
  File "e:\projekte\pynwb\src\pynwb\form\utils.py", line 375, in func_call
    return func(self, **parsed['args'])
  File "e:\projekte\pynwb\src\pynwb\form\validate\validator.py", line 221, in validate
    errors = validator.validate(attr_val)
  File "e:\projekte\pynwb\src\pynwb\form\utils.py", line 375, in func_call
    return func(self, **parsed['args'])
  File "e:\projekte\pynwb\src\pynwb\form\validate\validator.py", line 190, in validate
    if not check_type(spec.dtype, dtype):
  File "e:\projekte\pynwb\src\pynwb\form\validate\validator.py", line 78, in check_type
    received in 'ascii'
TypeError: 'in <string>' requires string as left operand, not numpy.dtype
(py36)
```

After this is fixed the validation tool should also be run as part of building the gallery files I guess.

### PR DESCRIPTION
**Pull request by ajtritt**
## Motivation
The validator can't validate files because it does not have support references and links. 

fix #698 
fix #747 
fix #208 
fix #715 

## Checklist

- [X] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured the PR description clearly describes problem and the solution?
- [X] Is your contribution compliant with our coding style ? This can be checked running `flake8` from the source directory.
- [X] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [X] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ?

### CODE REVIEW

**Comment by t-b** [comment]
@ajtritt Thanks, looks like you made big leap forward. I've added two more changes for improving the validation experience and also cleanup my part of the history via rebase.

From looking at the diff via `git log -p --reverse --color-moved --color-moved-ws=allow-indentation-change dev..` it looks like the ValidatorMap class is mostly the same, right?

**Comment by t-b** [comment]
@ajtritt One of the changes is that now see the validation errors are printed out when doing `python test.py --example`.

**Comment by ajtritt** [comment]
@t-b 

> It looks like the ValidatorMap class is mostly the same, right?

Yes, it didn't change much

**Review by oruebel — DISMISSED** [review]
Thanks for the hard work to fix the validator and several other bugs. Looks good to me. 

It would be nice to add doctring for ``__convert_dtype``, ``IllagelLinkError`` class, ``IncorrectDataType``` class, and the functions of the Validator class but not critical. This looks good to merge.

**Comment by t-b** [comment]
@ajtritt Ahh too late. I'll give that a shot in the next days and report back if I find any issues.

**Pull request merged**
