### PR TITLE
NWBContainer: Remove source attribute

### PR DESCRIPTION
**Pull request by t-b**
The source attribute is currently a free text entry designed for
provenance attribution.

Experienced showed that this was either mostly ignored or heavily
misused, e.g. sneaking in additional metadata.

Potential readers also don't benefit from the free text approach as it
is difficult to understand the contents without any rules on how to
interpret it.

So let's remove it.

All current users of source can either switch to description or
comments for NWBContainer.

### CODE REVIEW

**Comment by t-b** [comment]
Sorry for the late PR, this was supposed to be finished earlier. And also sorry for the diff, this is as much fun reviewing than doing...

**Comment by bendichter** [comment]
@t-b holy poop you actually did it! Thanks for tackling this, it is a great service to the project. I'll look through it now

**Comment by oruebel** [comment]
@t-b thanks for the help!

**Comment by nicain** [comment]
Many have tried (including myself!), but only @t-b has succeeded!!

**Review by bendichter — APPROVED** [review]

**Comment by t-b** [comment]
Thanks all for your kind words!

**Review by ajtritt — APPROVED** [review]
f*&# yeah!

**Pull request merged**
