### PR TITLE
Add support for device description and manufacturer

### PR DESCRIPTION
**Pull request by rly**
See https://github.com/NeurodataWithoutBorders/nwb-schema/pull/326

### CODE REVIEW

**Review by oruebel — APPROVED** [review]

**Comment by lvsltz** [comment]
What is the right combination of versions to have these new attributes? I am not able to have them written to nwb.

**Comment by t-b** [comment]
@lvsltz Did you try https://github.com/NeurodataWithoutBorders/pynwb/pull/1146?

**Comment by lvsltz** [comment]
Oh, I see. Thanks!

**Comment by lvsltz** [comment]
This doesn't seem to work with `pynwb==1.3.0` and `hdmf==1.6.1`.

**Comment by rly** [comment]
Thanks @lvsltz . You're correct - the new fields cannot be set. I created a new ticket here: #1208

**Pull request merged**
