### PR TITLE
Add test for validation cli

### LINKED ISSUE #1161: Enhance validation documentation
Looking at https://pynwb.readthedocs.io/en/stable/validation.html shows only a very short description. Enhance that broadly and also include hints for checking of the embedded schema.

### LINKED ISSUE #1162: Add tests for validating NWB files using the CLI interface
As recent bug reports revealed using `python -m pynwb.validate` vs. the validate method https://github.com/NeurodataWithoutBorders/pynwb/blob/a41eaee7b75405f5aab5d4e6c07709a94feb28c8/src/pynwb/__init__.py#L194 has different behaviour depending on the state of the loaded namespaces.

As a first step it would be good to add some validation tests using [subprocess](https://docs.python.org/3.8/library/subprocess.html) for the CLI interface to https://github.com/NeurodataWithoutBorders/pynwb/blob/a41eaee7b75405f5aab5d4e6c07709a94feb28c8/test.py#L74.

Needs probably to wait until https://github.com/NeurodataWithoutBorders/pynwb/tree/fix/validate_default is proposed and merged.

### LINKED ISSUE #1166: File Validation Error
## Description
When I try to validate my NWB files, I get a value error for the namespace.

## Steps to Reproduce
1) Create NWB file in this tutorial:
https://pynwb.readthedocs.io/en/stable/tutorials/domain/ecephys.html#sphx-glr-tutorials-domain-ecephys-py

2) Attempt validation in Jupyter/command prompt. 

3) Observe error: 
ValueError: data type 'NWBFile' not found in namespace hdmf-common

Jupyter:
! python -m pynwb.validate ecephys_example.nwb

Command prompt:
python -m pynwb.validate ecephys_example.nwb

## Environment

    Python Executable: Python
    Python Version: Python 3.7.5
    Operating System: Windows
    HDMF Version: Version of PyNWB used: 1.1.2

## Checklist

- [ X] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?
- [X ] Have you included a brief and descriptive title?
- [ X] Have you included a clear description of the problem you are trying to solve?
- [ X] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [X ] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

### PR DESCRIPTION
**Pull request by t-b**
Close #1162.
Close #1161.
Close #1166.

### CODE REVIEW

**Comment by t-b** [comment]
@rly I've cherry picked your fix for #1157. And it seems to fix the issues. Could you elaborate why it is the correct fix? The current commit message is a bit on the shorter side of things.

**Comment by rly** [comment]
@t-b The previous code validated files against both PyNWB and HDMF namespaces. `available_namespaces` returns `['core', 'hdmf-common']`. However, PyNWB types will not validate against the HDMF namespace because the types are missing the data type key `'data_type'` that is necessary for validation. The PyNWB core schema includes hdmf.common, so validating against the pynwb namespace will also validate the hdmf.common types. For example, when a `VectorData` is written, it is written with attributes `'namespace=core'` and `'neurodata_type=VectorData'` without mention of hdmf. So, we need only validate files against the PyNWB core namespace.

**Comment by t-b** [comment]
@rly Thanks! I'll include your description in the commit message.

**Comment by t-b** [comment]
@rly I've updated the commit message. I would like to handle https://github.com/NeurodataWithoutBorders/pynwb/issues/1058 in a separate PR. Reason being that this PR is already IMHO a pure improvement.

**Review by rly — APPROVED** [review]

**Pull request merged**
