### PR TITLE
Adding 1p ophys tutorial

### PR DESCRIPTION
**Pull request by bendichter**
## Motivation

* Add `OnePhotonSeries` to tutorial ophys tutorial
* Improve styling, fix some links, and move ophys tutorial towards current best practices

## Checklist

- [x] Did you update CHANGELOG.md with your changes?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR clearly describes the problem and the solution?
- [x] Is your contribution compliant with our coding style? This can be checked running `flake8` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [x] Have you included the relevant issue number using "Fix #XXX" notation where XXX is the issue number? By including "Fix #XXX" you allow GitHub to close issue #XXX when the PR is merged.

### CODE REVIEW

**Comment by bendichter** [comment]
```pytb
Traceback (most recent call last):
  File "test.py", line 115, in __run_example_tests_helper
    _import_from_file(script)
  File "test.py", line 63, in _import_from_file
    return imp.load_source(os.path.basename(script), script)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "docs/gallery/domain/ophys.py", line 31, in <module>
    from pynwb.ophys import (
ImportError: cannot import name 'OnePhotonSeries' from 'pynwb.ophys' (/home/runner/work/pynwb/pynwb/.tox/gallery-py37-minimum/lib/python3.7/site-packages/pynwb/ophys.py)
```

not sure why I am getting this error. The file runs fine locally.

**Comment by oruebel** [comment]
> not sure why I am getting this error. The file runs fine locally.

Not sure, but it looks like maybe the workflow is for some reason installing PyNWB 2.2

https://github.com/NeurodataWithoutBorders/pynwb/actions/runs/4375905634/jobs/7657259083#step:6:447

@mavaylon1 @rly looking at https://anaconda.org/conda-forge/pynwb it looks like PyNWB 2.3 may not be released on conda?

**Comment by bendichter** [comment]
Are the docs tests using a conda release instead of installing from the PR? In that case, even after the conda release is fixed, this PR will still fail because the tutorials requires a minor fix to the API. I suppose I could separate that into another PR.

**Comment by rly** [comment]
I believe #1679 is affecting the CI errors.

**Review by rly — APPROVED** [review]

**Pull request merged**
