### PR TITLE
Include test related files to the packaging

### LINKED ISSUE #607: Please distribute tests/ within your source releases on PyPI
ATM tarballs on pypi seems to lack `tests/`:
```
$> tar -tzvf <(wget -O- -q https://files.pythonhosted.org/packages/6f/f2/5802890d6d1706dca27b69eac298b82e5c61af620d570be83709639e4cdf/pynwb-0.4.1.tar.gz) | grep test
>
```
so redistributors (e.g. Debian) cannot assure correct operation of the pynwb, and would need to base their distribution on dumps of this git repository

### PR DESCRIPTION
**Pull request by dorukozturk**
## Motivation

Fixes #607 
Distribute test files as part of source releases. 

Next time we release pynwb, it should have test files.

### CODE REVIEW

**Comment by dorukozturk** [comment]
@yarikoptic This PR adds the necessary test files as part of pynwb's source release.

**Comment by yarikoptic** [comment]
Thanks, didn't know about `graft`

**Comment by dorukozturk** [comment]
@bendichter This includes all the test related files for pynwb to the source distribution. Can we merge this?

**Review by bendichter — APPROVED** [review]

**Comment by bendichter** [comment]
I wasn't around for the decision to leave tests out of the pypi source, so I don't know the reasons for that decision. What is the motivation for this change? If we are going to make this change, we should also change the documentation: https://pynwb.readthedocs.io/en/latest/getting_started.html#for-developers

**Review by bendichter — CHANGES_REQUESTED** [review]
Will this require a change to the docs?

**Comment by dorukozturk** [comment]
@bendichter In order to run the tests of pynwb we have to clone the repository because we were not including our tests files to the package. 
I don't think a documentation change is needed. This is simply for @yarikoptic to be able to download the tar file from pypi and run the tests without dealing with downloading from github. Also it seems like it is good practice. I saw packages like flask and django are including their tests files to their packaging.

**Review by bendichter — APPROVED** [review]

**Comment by yarikoptic** [comment]
FWIW, in my experience it is the majority of python projects which include tests not only within their source distribution but within their python package.  Moreover it is frequent to have `tests/` directories spread around the code to localize tests to the corresponding submodules.  See e.g.
```shell

~ > ls -d proj/numpy/**/tests          
proj/numpy/numpy/compat/tests/     proj/numpy/numpy/ma/tests/
proj/numpy/numpy/core/tests/       proj/numpy/numpy/matrixlib/tests/
proj/numpy/numpy/distutils/tests/  proj/numpy/numpy/polynomial/tests/
proj/numpy/numpy/f2py/tests/       proj/numpy/numpy/random/tests/
proj/numpy/numpy/fft/tests/        proj/numpy/numpy/testing/tests/
proj/numpy/numpy/lib/tests/        proj/numpy/numpy/tests/
proj/numpy/numpy/linalg/tests/

~ > ls -d proj/scipy/**/tests          
proj/scipy/scipy/_build_utils/tests/
proj/scipy/scipy/_lib/tests/
proj/scipy/scipy/cluster/tests/
proj/scipy/scipy/constants/tests/
proj/scipy/scipy/fftpack/tests/
proj/scipy/scipy/integrate/tests/
proj/scipy/scipy/interpolate/tests/
proj/scipy/scipy/io/arff/tests/
proj/scipy/scipy/io/harwell_boeing/tests/
proj/scipy/scipy/io/matlab/tests/
proj/scipy/scipy/io/tests/
proj/scipy/scipy/linalg/tests/
proj/scipy/scipy/misc/tests/
proj/scipy/scipy/ndimage/tests/
proj/scipy/scipy/odr/tests/
proj/scipy/scipy/optimize/_trustregion_constr/tests/
proj/scipy/scipy/optimize/tests/
proj/scipy/scipy/signal/tests/
proj/scipy/scipy/sparse/csgraph/tests/
proj/scipy/scipy/sparse/linalg/dsolve/tests/
proj/scipy/scipy/sparse/linalg/eigen/arpack/tests/
proj/scipy/scipy/sparse/linalg/eigen/lobpcg/tests/
proj/scipy/scipy/sparse/linalg/isolve/tests/
proj/scipy/scipy/sparse/linalg/tests/
proj/scipy/scipy/sparse/tests/
proj/scipy/scipy/spatial/tests/
proj/scipy/scipy/spatial/transform/tests/
proj/scipy/scipy/special/tests/
proj/scipy/scipy/stats/tests/

~ > ls -d proj/datalad/datalad/datalad/**/tests
proj/datalad/datalad/datalad/cmdline/tests/
proj/datalad/datalad/datalad/customremotes/tests/
proj/datalad/datalad/datalad/distribution/tests/
proj/datalad/datalad/datalad/downloaders/tests/
proj/datalad/datalad/datalad/interface/tests/
proj/datalad/datalad/datalad/metadata/extractors/tests/
proj/datalad/datalad/datalad/metadata/tests/
proj/datalad/datalad/datalad/plugin/tests/
proj/datalad/datalad/datalad/resources/website/tests/
proj/datalad/datalad/datalad/support/tests/
proj/datalad/datalad/datalad/tests/
proj/datalad/datalad/datalad/ui/tests/
```
It makes it 
- easy to run a subset of tests related to specific submodule
- possible to test module "as installed" on particular system (just e.g. run `python -m nose -s -v numpy` on your box) to verify correct operation/integration

So you might like to adopt that strategy as well.

**Comment by dorukozturk** [comment]
I think that will be the case once we push the new release on pypi. The last release was done before this PR.

**Comment by bendichter** [comment]
Thanks for the input @yarikoptic and @dorukozturk. I think you are right that we should include tests with the code.  They will be included in the next release.

**Pull request merged**
