### PR TITLE
Install tox on travis

### LINKED ISSUE #584: MacOS build test failing
## Bug

[MacOS badge on README](https://travis-ci.org/NeurodataWithoutBorders/pynwb/jobs/412157348) marks build as failing. It looks like it can't find `tox`? I think it's a problem with the server or test setup rather than `pynwb`. I'm out of my depth. Kitware people?

### PR DESCRIPTION
**Pull request by dorukozturk**
## Motivation

Fixes #584

### CODE REVIEW

**Comment by jcfr** [comment]
For some reason, travisCI didn't start ...

**Comment by dorukozturk** [comment]
@jcfr We only run the travis tests once they are merged :)

**Comment by jcfr** [comment]
> We only run the travis tests once they are merged :)

Thanks for the reminder :+1:

**Review by jcfr — APPROVED** [review]

**Comment by bendichter** [comment]
@jcfr @dorukozturk thanks guys!

**Pull request merged**
