### PR TITLE
update requirements.txt for python3

### PR DESCRIPTION
**Pull request by ukos-git**
numpy 1.14.2 has problems installing in python3.7.
This fix lets pynwb install again on a clean venv.

see #651

### CODE REVIEW

**Comment by dorukozturk** [comment]
See #659

**Comment by dorukozturk** [comment]
Ok this started to make sense. Right now we are installing tox 3.5.1 on conda. Though tox released 3.5.2 which fixes this issue. So I will revert my PR from yesterday because the latest tox is working for us now. Once they get https://github.com/conda-forge/tox-feedstock/pulls in we should be good.

**Comment by ukos-git** [comment]
@dorukozturk this issue is not quite related. It is targetting towards a wheels->cpython compiler issue https://github.com/numpy/numpy/issues/10500#issuecomment-393949228 

But it is only happening in python 3.**7** , which is not supported by pynwb but the changes will not hurt. We could either close this issue here due to the not supported python version or update the numpy package (and pandas, which goes together) to the newer subsubversion as suggested.

**Comment by dorukozturk** [comment]
@ukos-git I was just pointing why the miniconda tests are failing. I haven't checked the context of this PR yet :)

**Comment by ukos-git** [comment]
I understand. I was just clarifying.

**Review by ajtritt — APPROVED** [review]

**Comment by ajtritt** [comment]
Thanks for tackling this @ukos-git

**Pull request merged**
