### PR TITLE
Add optional link to Device in ImageSeries

### PR DESCRIPTION
**Pull request by rly**
## Motivation

Support https://github.com/NeurodataWithoutBorders/nwb-schema/pull/454

Requires https://github.com/NeurodataWithoutBorders/nwb-schema/pull/454 to be merged

## Checklist

- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR description clearly describes problem and the solution?
- [x] Is your contribution compliant with our coding style? This can be checked running `flake8` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [x] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number?

### CODE REVIEW

**Comment by bendichter** [comment]
what about the descendants, `TwoPhotonSeries` and `OpticalSeries`? Will they support devices?

**Comment by rly** [comment]
Thanks. I just added that. I also added it in `ImageMaskSeries` which is the other subclass of `ImageSeries` because based on the schema you can have an optional link to a Device in a ImageMaskSeries. It doesn't really make sense to, but currently we have no way in the schema to say that an optional link in a parent type is not allowed in the child type.

**Comment by rly** [comment]
I guess since it doesn't make sense to have a separate link to a `Device` in `ImageMaskSeries`, we can restrict that in the API. It depends on whether we want the API to support the full flexibility of the schema or not.

**Comment by bendichter** [comment]
If we leave it out, then it won't be supported on read, will it? I think if someone creates a file that NWB supports, we should be able to read it. We can use the doc of that arg to say that this field would likely not be needed.

**Comment by rly** [comment]
Right, if we leave it out, it would not be supported on read. Good point

**Comment by oruebel** [comment]
Removing/hiding attributes inherited from a parent type should not be allowed. If an attribute on a parent class does not make sense in a child class then that typically points to problem in the model.

**Review by bendichter — APPROVED** [review]

**Pull request merged**
