### PR TITLE
CurrentClampSeries: Remove duplicated timestamps parameter

### PR DESCRIPTION
**Pull request by t-b**
Introduced in 0d5878e7 (added macros to pynwb container classes,
2017-10-25) and found by accident when reading the documentation.

Is there any use in duplicated arguments? If not maybe teaching `@docval` to complain can prevent that in the future.

### CODE REVIEW

**Comment by bendichter** [comment]
@t-b Sounds like a good idea to me. Would you mind making an issue for it?

**Review by ajtritt — APPROVED** [review]

**Comment by t-b** [comment]
@ajtritt Thx. The failing tests look unrelated to my changes.

**Comment by t-b** [comment]
@bendichter @ajtritt merge?

**Review by ajtritt — APPROVED** [review]

**Comment by bendichter** [comment]
@t-b thanks for the reminder

**Pull request merged**
