### PR TITLE
WIP: Support IPNWB nwb files better

### PR DESCRIPTION
**Pull request by t-b**
- [ ] Fix "expected `text` got `ascii`" validation for old NWBv2 files, requires 

Branch: https://github.com/t-b/hdmf-common-schema/tree/use-text-as-encoding-for-dynamic-table-column-names.
Issue: https://github.com/hdmf-dev/hdmf-common-schema/issues/4

### CODE REVIEW

**Comment by t-b** [comment]
@ajtritt The commit c66d03f reverses what you did earlier on. Do you remember why you did that? Is there a way to tell the validator that ascii is a valid dtype if text is expected?

**Comment by oruebel** [comment]
>  Is there a way to tell the validator that ascii is a valid dtype if text is expected?

I think that would be in HDMF in the ``check_type`` function of ``validator.py`` https://github.com/hdmf-dev/hdmf/blob/5a864ef997f000d3a8137736ddfc73de33683e3f/src/hdmf/validate/validator.py#L44

**Comment by oruebel** [comment]
What is the status of this PR?

**Comment by t-b** [comment]
@oruebel Currently on the backlog. You can close it for now if you like.

**Comment by t-b** [comment]
Fixed via https://github.com/hdmf-dev/hdmf-common-schema/pull/5.

**Pull request closed without merging**
