### PR TITLE
Add coverage

### LINKED ISSUE #132: CI: Add support for reporting coverage
* [x] Add `codecov`, `coverage` and `pytest-cov` as dev dependencies
* [x] Update `pytest.ini` (for example, see [here](https://github.com/scikit-build/scikit-build/blob/b40067617883bf1128924df70ab0d6eb8f955c9e/pytest.ini#L3))
* [x] Add `.coveragerc` (for example, see [here](https://github.com/scikit-build/scikit-build/blob/master/.coveragerc))
* [x] submit to codecov.io (for example, see [here](https://github.com/scikit-build/scikit-build/blob/b40067617883bf1128924df70ab0d6eb8f955c9e/scikit-ci.yml#L45-L47))
* [x] Add badge to readme.rst

### PR DESCRIPTION
**Pull request by dorukozturk**
Fixes #132.

### CODE REVIEW

**Comment by dorukozturk** [comment]
@jcfr PTAL.

**Comment by jcfr** [comment]
Could you submit coverage from all CIs ? 

codecov will then take care of aggregating them. This will allow to account for code branch specific to each platform

**Comment by dorukozturk** [comment]
@jcfr I think this is ready for the final review. PTAL

**Review by jcfr — DISMISSED** [review]
After integrating the #144 and rebasing. LGTM

coverage badge could be added under a `Overall Health` section

**Pull request merged**
