### PR TITLE
Fix wheel install tests

### PR DESCRIPTION
**Pull request by dorukozturk**
## Motivation

Fixes broken wheel installation tests.
The reason is: https://github.com/tox-dev/tox/issues/1042

### CODE REVIEW

**Comment by dorukozturk** [comment]
@oruebel This fixes the tests. Please take a look and merge if it looks good.

**Review by oruebel — APPROVED** [review]

**Comment by oruebel** [comment]
Thanks @dorukozturk for the quick fix

**Comment by ukos-git** [comment]
@dorukozturk Thank you for finding and fixing this. pythonXX is working now but miniconda (which was passing before) gets the same errors as pythonXX before. Does miniconda have a spearate settings file?

**Comment by ukos-git** [comment]
https://github.com/NeurodataWithoutBorders/pynwb/blob/23781ef9e6f7b8d4a8147e3d8be99d69c74a0b91/.circleci/config.yml#L74

**Comment by dorukozturk** [comment]
@ukos-git Good catch. I must have missed that. I am submitting another PR.

**Comment by ukos-git** [comment]
https://github.com/NeurodataWithoutBorders/pynwb/pull/661

**Comment by bendichter** [comment]
I'm getting errors on miniconda for #627 and I suspect it has to do with this PR

```
#!/bin/bash -eo pipefail
tox -e $TEST_WHEELINSTALL_ENV --recreate --installpkg dist/*-none-any.whl
wheelinstall-py27 create: /root/project/.tox/wheelinstall-py27
wheelinstall-py27 installdeps: null
wheelinstall-py27 inst: /root/project/.tox/.tmp/1-pynwb-0.5.1.post0.dev84-py2.py3-none-any.whl
ERROR: invocation failed (exit code 2), logfile: /root/project/.tox/wheelinstall-py27/log/wheelinstall-py27-2.log
ERROR: actionid: wheelinstall-py27
msg: installpkg
cmdargs: '/root/project/.tox/wheelinstall-py27/bin/pip install -U --exists-action w /root/project/.tox/.tmp/1-pynwb-0.5.1.post0.dev84-py2.py3-none-any.whl'

Processing ./.tox/.tmp/1-pynwb-0.5.1.post0.dev84-py2.py3-none-any.whl
Collecting ruamel.yaml (from 1==pynwb)
  Downloading https://files.pythonhosted.org/packages/e4/30/7a6269ccc526b1f580d498acf2cdf2ea926de79b4a2f5c5ee3ca46219cbb/ruamel.yaml-0.15.72-cp27-cp27mu-manylinux1_x86_64.whl (607kB)
Collecting requests (from 1==pynwb)
  Downloading https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl (91kB)
Collecting numpy (from 1==pynwb)
  Downloading https://files.pythonhosted.org/packages/40/c5/f1ed15dd931d6667b40f1ab1c2fe1f26805fc2b6c3e25e45664f838de9d0/numpy-1.15.2-cp27-cp27mu-manylinux1_x86_64.whl (13.8MB)
Collecting pandas (from 1==pynwb)
  Downloading https://files.pythonhosted.org/packages/b7/e3/f52d484244105fa3d558ce8217a5190cd3d40536076bef66d92d01566325/pandas-0.23.4-cp27-cp27mu-manylinux1_x86_64.whl (8.9MB)
Collecting h5py (from 1==pynwb)
  Downloading https://files.pythonhosted.org/packages/33/0c/1c5dfa85e05052aa5f50969d87c67a2128dc39a6f8ce459a503717e56bd0/h5py-2.8.0-cp27-cp27mu-manylinux1_x86_64.whl (2.7MB)
Collecting python-dateutil (from 1==pynwb)
  Downloading https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl (211kB)
Requirement already satisfied, skipping upgrade: six in ./.tox/wheelinstall-py27/lib/python2.7/site-packages (from 1==pynwb) (1.11.0)
Collecting ruamel.ordereddict; platform_python_implementation == "CPython" and python_version <= "2.7" (from ruamel.yaml->1==pynwb)
  Using cached https://files.pythonhosted.org/packages/f3/2c/fa6d75dc459b371ed3b88fdbf8042785ce1655073c884fd97bdbb9f48e01/ruamel.ordereddict-0.4.13-cp27-cp27mu-manylinux1_x86_64.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->1==pynwb)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests->1==pynwb)
  Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl (58kB)
Collecting urllib3<1.24,>=1.21.1 (from requests->1==pynwb)
  Downloading https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl (133kB)
Collecting certifi>=2017.4.17 (from requests->1==pynwb)
  Downloading https://files.pythonhosted.org/packages/df/f7/04fee6ac349e915b82171f8e23cee63644d83663b34c539f7a09aed18f9e/certifi-2018.8.24-py2.py3-none-any.whl (147kB)
Collecting pytz>=2011k (from pandas->1==pynwb)
  Using cached https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl
Installing collected packages: ruamel.ordereddict, ruamel.yaml, chardet, idna, urllib3, certifi, requests, numpy, python-dateutil, pytz, pandas, h5py, 1
Exception:
Traceback (most recent call last):
  File "/root/project/.tox/wheelinstall-py27/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/root/project/.tox/wheelinstall-py27/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 366, in run
    use_user_site=options.use_user_site,
  File "/root/project/.tox/wheelinstall-py27/lib/python2.7/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/root/project/.tox/wheelinstall-py27/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 760, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/root/project/.tox/wheelinstall-py27/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 382, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/root/project/.tox/wheelinstall-py27/lib/python2.7/site-packages/pip/_internal/wheel.py", line 326, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: 1==pynwb .dist-info directory not found

wheelinstall-py27 installed: certifi==2018.8.24,chardet==3.0.4,h5py==2.8.0,idna==2.7,null==0.6.1,numpy==1.15.2,pandas==0.23.4,pynwb==0.5.1.post0.dev84,python-dateutil==2.7.3,pytz==2018.5,requests==2.19.1,ruamel.ordereddict==0.4.13,ruamel.yaml==0.15.72,six==1.11.0,urllib3==1.23
___________________________________ summary ____________________________________
ERROR:   wheelinstall-py27: InvocationError for command /root/project/.tox/wheelinstall-py27/bin/pip install -U --exists-action w /root/project/.tox/.tmp/1-pynwb-0.5.1.post0.dev84-py2.py3-none-any.whl (see /root/project/.tox/wheelinstall-py27/log/wheelinstall-py27-2.log) (exited with code 2)
Exited with code 1
```

**Comment by ukos-git** [comment]
> I'm getting errors on miniconda for #627 and I suspect it has to do with this PR

It's more exactly this PR #661 that fixes it if someone approves and merges it.

**Pull request merged**
