### PR TITLE
Allow empty data with non-empty VectorIndex

### LINKED ISSUE #880: add_trial_column with empty data
## 1) Bug

```
from datetime import datetime
from dateutil.tz import tzlocal
import os
from pynwb import NWBFile, register_class, docval, load_namespaces, popargs, NWBHDF5IO
from pynwb.spec import NWBNamespaceBuilder, NWBGroupSpec, NWBAttributeSpec, NWBDatasetSpec
from pynwb.file import LabMetaData

nwbfile = NWBFile("a file with header data", "NB123A", datetime(2017, 5, 1, 12, 0, 0, tzinfo=tzlocal()))
data = []
index = [0,0,0]
nwbfile.add_trial(start_time=.1, stop_time=.2)
nwbfile.add_trial(start_time=.3, stop_time=.4)
nwbfile.add_trial(start_time=.5, stop_time=.6)
nwbfile.add_trial_column(name='example', description='Hi', data=data, index=index)

print(nwbfile.trials.to_dataframe())
```

results in:

```
    nwbfile.add_trial_column(name='example', description='Hi', data=data, index=index)
  File "/home/nicholasc/anaconda2/lib/python2.7/site-packages/hdmf/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/home/nicholasc/projects/pynwb/src/pynwb/file.py", line 530, in add_trial_column
    call_docval_func(self.trials.add_column, kwargs)
  File "/home/nicholasc/anaconda2/lib/python2.7/site-packages/hdmf/utils.py", line 274, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/home/nicholasc/anaconda2/lib/python2.7/site-packages/hdmf/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/home/nicholasc/projects/pynwb/src/pynwb/core.py", line 1178, in add_column
    raise ValueError("cannot pass non-empty index with empty data to index")
ValueError: cannot pass non-empty index with empty data to index
```

If you change data = [] to data=[None], you ge the desired behavior:

```
example  start_time  stop_time
id                               
0       []         0.1        0.2
1       []         0.3        0.4
2       []         0.5        0.6
```

However, on write this little hack results in:

```
Could not create dataset lick_times in /intervals/trials with shape (1,), dtype <class 'NoneType'>, and iosettings . Object dtype dtype('O') has no native HDF5 equivalent
```

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

### PR DESCRIPTION
**Pull request by ajtritt**
## Motivation

fix #880 

## How to test the behavior?
run tests

## Checklist

- [X] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured the PR description clearly describes problem and the solution?
- [X] Is your contribution compliant with our coding style ? This can be checked running `flake8` from the source directory.
- [X] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [X] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ?

### CODE REVIEW

**Comment by t-b** [comment]
@ajtritt Thanks for the quick fix.

My example unfortunately still fails

```python
from pynwb import NWBHDF5IO
from datetime import datetime
from dateutil.tz import tzlocal
from pynwb import NWBFile
import numpy as np
from pynwb.icephys import CurrentClampStimulusSeries
from pynwb.icephys import VoltageClampSeries
from pynwb.epoch import TimeIntervals

nwbfile = NWBFile('my first synthetic recording', 'EXAMPLE_ID', datetime.now(tzlocal()),
                  experimenter='Dr. Bilbo Baggins',
                  lab='Bag End Laboratory',
                  institution='University of Middle Earth at the Shire',
                  experiment_description='I went on an adventure with thirteen dwarves to reclaim vast treasures.',
                  session_id='LONELYMTN')

device = nwbfile.create_device(name='Heka ITC-1600')
elec = nwbfile.create_ic_electrode(name="elec0",
                                   description='a mock intracellular electrode',
                                   device=device)

ccss = CurrentClampStimulusSeries(
    name="ccss", data=[1, 2, 3, 4, 5], unit='A',
    starting_time=123.6, rate=10e3, electrode=elec, gain=0.02, sweep_number=15)

nwbfile.add_stimulus(ccss)

vcs = VoltageClampSeries(
    name='vcs', data=[0.1, 0.2, 0.3, 0.4, 0.5],
    unit='A', conversion=1e-12, resolution=np.nan, starting_time=123.6, rate=20e3,
    electrode=elec, gain=0.02, capacitance_slow=100e-12, resistance_comp_correction=70.0,
    capacitance_fast=np.nan, resistance_comp_bandwidth=np.nan, resistance_comp_prediction=np.nan,
    whole_cell_capacitance_comp=np.nan, whole_cell_series_resistance_comp=np.nan, sweep_number=15)

nwbfile.add_acquisition(vcs)

nwbfile.add_trial_column(name='stim', description='the visual stimuli during the trial')
nwbfile.add_trial_column(name='ts', description='Matching TimeSeries')

# FIXME fails
# nwbfile.add_trial(start_time=6.0, stop_time=8.0, stim='desert', ts=[])
# FIXME fails as well
nwbfile.add_trial(start_time=6.0, stop_time=8.0, stim='desert', ts=None)

print(nwbfile.trials.to_dataframe())

io = NWBHDF5IO('icephys_example.nwb', 'w')
io.write(nwbfile)
io.close()
```

```
$ python icephys.py
    start_time    stim  stop_time    ts
id
0          6.0  desert        8.0  None
Traceback (most recent call last):
  File "icephys.py", line 47, in <module>
    io.write(nwbfile)
  File "e:\projekte\hdmf\src\hdmf\utils.py", line 388, in func_call
    return func(self, **parsed['args'])
  File "e:\projekte\hdmf\src\hdmf\backends\hdf5\h5tools.py", line 196, in write
    call_docval_func(super(HDF5IO, self).write, kwargs)
  File "e:\projekte\hdmf\src\hdmf\utils.py", line 281, in call_docval_func
    return func(*fargs, **fkwargs)
  File "e:\projekte\hdmf\src\hdmf\utils.py", line 388, in func_call
    return func(self, **parsed['args'])
  File "e:\projekte\hdmf\src\hdmf\backends\io.py", line 40, in write
    self.write_builder(f_builder, **kwargs)
  File "e:\projekte\hdmf\src\hdmf\utils.py", line 388, in func_call
    return func(self, **parsed['args'])
  File "e:\projekte\hdmf\src\hdmf\backends\hdf5\h5tools.py", line 412, in write_builder
    self.write_group(self.__file, gbldr)
  File "e:\projekte\hdmf\src\hdmf\utils.py", line 388, in func_call
    return func(self, **parsed['args'])
  File "e:\projekte\hdmf\src\hdmf\backends\hdf5\h5tools.py", line 555, in write_group
    self.write_group(group, sub_builder)
  File "e:\projekte\hdmf\src\hdmf\utils.py", line 388, in func_call
    return func(self, **parsed['args'])
  File "e:\projekte\hdmf\src\hdmf\backends\hdf5\h5tools.py", line 560, in write_group
    self.write_dataset(group, sub_builder)
  File "e:\projekte\hdmf\src\hdmf\utils.py", line 388, in func_call
    return func(self, **parsed['args'])
  File "e:\projekte\hdmf\src\hdmf\backends\hdf5\h5tools.py", line 752, in write_dataset
    dset = self.__list_fill__(parent, name, data, options)
  File "e:\projekte\hdmf\src\hdmf\backends\hdf5\h5tools.py", line 875, in __list_fill__
    raise_from(Exception(msg), exc)
  File "C:\Anaconda2\lib\site-packages\six.py", line 737, in raise_from
    raise value
Exception: Could not create dataset ts in /intervals/trials with shape (1,), dtype <type 'NoneType'>, and iosettings . Object dtype dtype('O
') has no native HDF5 equivalent
```

Commenting the first one with the empty list gives

```
 File "e:\projekte\hdmf\src\hdmf\backends\io.py", line 39, in write
   f_builder = self.__manager.build(container, source=self.__source)
 File "e:\projekte\hdmf\src\hdmf\utils.py", line 388, in func_call
   return func(self, **parsed['args'])
 File "e:\projekte\hdmf\src\hdmf\build\map.py", line 159, in build
   result = self.__type_map.build(container, self, source=source)
 File "e:\projekte\hdmf\src\hdmf\utils.py", line 388, in func_call
   return func(self, **parsed['args'])
 File "e:\projekte\hdmf\src\hdmf\build\map.py", line 1559, in build
   builder = attr_map.build(container, manager, builder=builder, source=getargs('source', kwargs))
 File "e:\projekte\hdmf\src\hdmf\utils.py", line 388, in func_call
   return func(self, **parsed['args'])
 File "e:\projekte\hdmf\src\hdmf\build\map.py", line 765, in build
   self.__add_groups(builder, self.__spec.groups, container, manager, source)
 File "e:\projekte\hdmf\src\hdmf\build\map.py", line 973, in __add_groups
   self.__add_groups(sub_builder, spec.groups, container, build_manager, source)
 File "e:\projekte\hdmf\src\hdmf\build\map.py", line 989, in __add_groups
   self.__add_containers(builder, spec, attr_value, build_manager, source, container)
 File "e:\projekte\hdmf\src\hdmf\build\map.py", line 999, in __add_containers
   rendered_obj = build_manager.build(value, source=source)
 File "e:\projekte\hdmf\src\hdmf\utils.py", line 388, in func_call
   return func(self, **parsed['args'])
 File "e:\projekte\hdmf\src\hdmf\build\map.py", line 159, in build
   result = self.__type_map.build(container, self, source=source)
 File "e:\projekte\hdmf\src\hdmf\utils.py", line 388, in func_call
   return func(self, **parsed['args'])
 File "e:\projekte\hdmf\src\hdmf\build\map.py", line 1559, in build
   builder = attr_map.build(container, manager, builder=builder, source=getargs('source', kwargs))
 File "e:\projekte\hdmf\src\hdmf\utils.py", line 388, in func_call
   return func(self, **parsed['args'])
 File "e:\projekte\hdmf\src\hdmf\build\map.py", line 764, in build
   self.__add_datasets(builder, self.__spec.datasets, container, manager, source)
 File "e:\projekte\hdmf\src\hdmf\build\map.py", line 948, in __add_datasets
   self.__add_containers(builder, spec, attr_value, build_manager, source, container)
 File "e:\projekte\hdmf\src\hdmf\build\map.py", line 1032, in __add_containers
   self.__add_containers(builder, spec, container, build_manager, source, parent_container)
 File "e:\projekte\hdmf\src\hdmf\build\map.py", line 999, in __add_containers
   rendered_obj = build_manager.build(value, source=source)
 File "e:\projekte\hdmf\src\hdmf\utils.py", line 388, in func_call
   return func(self, **parsed['args'])
 File "e:\projekte\hdmf\src\hdmf\build\map.py", line 159, in build
   result = self.__type_map.build(container, self, source=source)
 File "e:\projekte\hdmf\src\hdmf\utils.py", line 388, in func_call
   return func(self, **parsed['args'])
 File "e:\projekte\hdmf\src\hdmf\build\map.py", line 1559, in build
   builder = attr_map.build(container, manager, builder=builder, source=getargs('source', kwargs))
 File "e:\projekte\hdmf\src\hdmf\utils.py", line 388, in func_call
   return func(self, **parsed['args'])
 File "e:\projekte\hdmf\src\hdmf\build\map.py", line 795, in build
   if self.__spec.dtype is None and self.__is_reftype(container.data):
 File "e:\projekte\hdmf\src\hdmf\build\map.py", line 828, in __is_reftype
   tmp = tmp[0]
ndexError: list index out of range
```

And I'm using the `enh/null_ref` branch of hdmf.

**Review by t-b — CHANGES_REQUESTED** [review]
MWE still fails

**Comment by rly** [comment]
The underlying issue with the MWE is that your new column "ts" has no data and no type associated with it (built-in columns have types explicitly written in the spec that can be used). On the backend, for h5py to create an empty dataset, [a type still needs to be provided](http://docs.h5py.org/en/stable/high/dataset.html#creating-and-reading-empty-or-null-datasets-and-attributes). 

We could default this to float, but now I'm not sure whether we should even support this functionality. It seems to me that if you add a column to a dynamic table and all the values in that column are None, that a warning or error of some sort should be thrown and the column should not be added to the file. And if we were to allow empty custom columns with a float default type, I think trying to change the values of these datasets down the road might be difficult.

@t-b @oruebel @ajtritt What do you think? Should this be a supported use case?

As an aside, currently, if trial columns are added but no trials are added, these warnings appear:
```
MissingRequiredWarning: empty dataset 'start_time' for 'trials' of type (TimeIntervals)
MissingRequiredWarning: empty dataset 'stop_time' for 'trials' of type (TimeIntervals)
MissingRequiredWarning: empty dataset 'id' for 'trials' of type (TimeIntervals)
```
and the file is written with empty datasets for the default attributes, e.g. `start_time`, with types inferred from the spec. The custom added attributes are not written.

**Comment by rly** [comment]
With the changes in https://github.com/hdmf-dev/hdmf/pull/121 to handle empty arrays with a specified dtype, instead of:
```python
nwbfile.add_trial(start_time=6.0, stop_time=8.0, stim='desert', ts=[])
```
I think you can do:
```python
nwbfile.add_trial(start_time=6.0, stop_time=8.0, stim='desert', ts=np.empty(dtype='float'))
```
For another example, see https://github.com/NeurodataWithoutBorders/pynwb/pull/1029/files and search for H5DataIO to see how to wrap this.

**Review by oruebel — DISMISSED** [review]

**Comment by rly** [comment]
@ajtritt I think this PR is good to go.

**Review by rly — DISMISSED** [review]

**Comment by rly** [comment]
On second thought... as I understand the PR, I don't think this ability should be allowed. Why have a non-empty index of all zeros without data? An index of 0 suggests there is at least one value in the column.

**Pull request closed without merging**
