### PR TITLE
validate against most specific namespaces

### PR DESCRIPTION
**Pull request by ajtritt**
## Motivation

Validate against _most-specific_ schemas from file i.e. do not validate against base specifications, as not all types will be in them. 

## How to test the behavior?
run `python -m pynwb.validate` on [this file](https://github.com/NeurodataWithoutBorders/pynwb/files/3691053/example_file_path.zip)

### CODE REVIEW

**Review by oruebel — DISMISSED** [review]

**Comment by t-b** [comment]
That file does not validate here.

I'm using
hdmf: 56ebfc30 (Bug/register container (#175), 2019-10-16)
pynwb: 03c84e57 (Merge branch 'dev' into bug/cmdline_validate, 2019-10-16)

and are getting

```
(pynwb) E:\projekte\pynwb>python -m pynwb.validate example_file_path.nwb
Validating example_file_path.nwb against cached namespace information using namespace mylab.
Traceback (most recent call last):
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "e:\projekte\pynwb\src\pynwb\validate.py", line 120, in <module>
    main()
  File "e:\projekte\pynwb\src\pynwb\validate.py", line 114, in main
    ret = ret or _validate_helper(io=io, namespace=ns)
  File "e:\projekte\pynwb\src\pynwb\validate.py", line 25, in _validate_helper
    errors = validate(**kwargs)
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\utils.py", line 453, in func_call
    return func(**parsed['args'])
  File "e:\projekte\pynwb\src\pynwb\__init__.py", line 179, in validate
    return validator.validate(builder)
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\validate\validator.py", line 238, in validate
    return validator.validate(builder)
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\validate\validator.py", line 476, in validate
    ret.extend(validator.validate(sub_builder))
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\validate\validator.py", line 444, in validate
    ret.extend(sub_val.validate(tmp))
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\validate\validator.py", line 444, in validate
    ret.extend(sub_val.validate(tmp))
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\validate\validator.py", line 377, in validate
    shape = get_shape(data)
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\data_utils.py", line 35, in get_shape
    return __get_shape_helper(data)
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\data_utils.py", line 20, in __get_shape_helper
    if len(data) and not isinstance(data[0], (text_type, binary_type)):
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\backends\hdf5\h5_utils.py", line 85, in __getitem__
    self.__swap_refs(rows)
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\backends\hdf5\h5_utils.py", line 94, in __swap_refs
    row[i] = getref(row[i])
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\backends\hdf5\h5_utils.py", line 97, in __get_ref
    return self.io.get_container(self.dataset.file[ref])
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\backends\hdf5\h5tools.py", line 332, in get_container
    container = self.manager.construct(builder)
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\build\map.py", line 204, in construct
    result = self.__type_map.construct(builder, self, parent)
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\build\map.py", line 1707, in construct
    attr_map = self.get_map(builder)
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\build\map.py", line 1634, in get_map
    container_cls = self.get_cls(obj)
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\build\map.py", line 1565, in get_cls
    return self.get_container_cls(namespace, data_type)
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\build\map.py", line 1486, in get_container_cls
    d = self.__get_cls_dict(parent_cls, fields, spec.name, spec.default_name)
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\build\map.py", line 1416, in __get_cls_dict
    dtype = self.__get_type(field_spec)
  File "C:\Users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\build\map.py", line 1371, in __get_type
    if spec.shape is None and spec.dims is None:
AttributeError: 'NWBGroupSpec' object has no attribute 'shape'

```

**Comment by ajtritt** [comment]
@t-b strange. I don't have that problem. I'm using:
pynwb: 03c84e578b6c09ea87f78d5fa0c8493f0bad41c2
hdmf: 44c02ea7f3666d68aa7402407c91e9503f0fd99b

@rly @bendichter @oruebel Do you still get the error?

**Review by t-b — APPROVED** [review]
Works now, looks like my previous error was local misconfiguration.

**Comment by t-b** [comment]
```
$ python -m pynwb.validate example_file_path.nwb
Validating example_file_path.nwb against cached namespace information using namespace ecog.
 - no errors found.
Validating example_file_path.nwb against cached namespace information using namespace mylab.
 - no errors found.
Validating example_file_path.nwb against cached namespace information using namespace test_multicontainerinterface.
 - no errors found.
```

**Comment by t-b** [comment]
@ajtritt Does that PR fix https://github.com/NeurodataWithoutBorders/pynwb/issues/1082?

**Comment by t-b** [comment]
@rly @ajtritt Retested and works. If there is anything I can do to get his merged feel free to ping me.

**Review by rly — APPROVED** [review]

**Comment by rly** [comment]
This looks good to merge @ajtritt. There are other problems with the validator, which I'll address in a separate PR.

**Pull request merged**
