### PR TITLE
fix ability to load cached namespaces

### LINKED ISSUE #541: saving/loading cached spec
Maybe I just don't know how to do it, but I am having trouble loading a cached spec in [this file](https://ucsf.box.com/s/po20z1x12rwqus5gl9vehe13ffjcbcjo).

I've tried:
```python
from pynwb import NWBHDF5IO, load_namespaces, get_type_map
fpath='/Users/bendichter/Desktop/Chang/data/EC125/EC125_B22.nwb'

type_map = get_type_map()
NWBHDF5IO.load_namespaces(type_map.namespace_catalog, fpath)
io = NWBHDF5IO(fpath,'r')
nwbfile = io.read()
```

and I get
```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-9f170db56d42> in <module>()
      2 
      3 type_map = get_type_map()
----> 4 NWBHDF5IO.load_namespaces(type_map.namespace_catalog, fpath)
      5 io = NWBHDF5IO(fpath,'r')
      6 nwbfile = io.read()

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py in load_namespaces(cls, namespace_catalog, path, namespaces)
     76             ns_group = ns_group[latest_version]
     77             reader = H5SpecReader(ns_group)
---> 78             namespace_catalog.load_namespaces('namespace', reader=reader)
     79         f.close()
     80 

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/spec/namespace.py in load_namespaces(self, **kwargs)
    398         for ns in namespaces:
    399             if ns['name'] in self.__namespaces:
--> 400                 raise KeyError("namespace '%s' already exists" % ns['name'])
    401         # now load specs into namespace
    402         for ns in namespaces:

KeyError: "namespace 'core' already exists"
```

But then if I define namespaces:
```python
from pynwb import NWBHDF5IO, load_namespaces, get_type_map
fpath='/Users/bendichter/Desktop/Chang/data/EC125/EC125_B22.nwb'

type_map = get_type_map()
NWBHDF5IO.load_namespaces(type_map.namespace_catalog, fpath, namespaces=['ecog'])
io = NWBHDF5IO(fpath,'r')
nwbfile = io.read()
```

I get this error:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-e78b0c3b6dfa> in <module>()
      3 
      4 type_map = get_type_map()
----> 5 NWBHDF5IO.load_namespaces(type_map.namespace_catalog, fpath, namespaces=['ecog'])
      6 io = NWBHDF5IO(fpath,'r')
      7 nwbfile = io.read()

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py in load_namespaces(cls, namespace_catalog, path, namespaces)
     76             ns_group = ns_group[latest_version]
     77             reader = H5SpecReader(ns_group)
---> 78             namespace_catalog.load_namespaces('namespace', reader=reader)
     79         f.close()
     80 

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/spec/namespace.py in load_namespaces(self, **kwargs)
    401         # now load specs into namespace
    402         for ns in namespaces:
--> 403             ret[ns['name']] = self.__load_namespace(ns, reader, types_key, resolve=resolve)
    404         self.__included_specs[namespace_path] = ret
    405         return ret

~/dev/pynwb/src/pynwb/form/spec/namespace.py in __load_namespace(self, namespace, reader, types_key, resolve)
    350                 if types_key in s:
    351                     dtypes = set(s[types_key])
--> 352                 self.__load_spec_file(reader, s['source'], catalog, dtypes=dtypes, resolve=resolve)
    353                 self.__included_sources.setdefault(ns_name, list()).append(s['source'])
    354             elif 'namespace' in s:

~/dev/pynwb/src/pynwb/form/spec/namespace.py in __load_spec_file(self, reader, spec_source, catalog, dtypes, resolve)
    318             specs = d.get('groups', list())
    319             for spec_dict in specs:
--> 320                 ret.extend(__reg_spec(self.__group_spec_cls, spec_dict))
    321             self.__loaded_specs[spec_source] = ret
    322         return ret

~/dev/pynwb/src/pynwb/form/spec/namespace.py in __reg_spec(spec_cls, spec_dict)
    306                 return
    307             if resolve:
--> 308                 self.__resolve_includes(spec_dict, catalog)
    309             spec_obj = spec_cls.build_spec(spec_dict)
    310             return catalog.auto_register(spec_obj, spec_source)

~/dev/pynwb/src/pynwb/form/spec/namespace.py in __resolve_includes(self, spec_dict, catalog)
    332             if parent_spec is None:
    333                 msg = "Cannot resolve include spec '%s' for type '%s'" % (dt_inc, dt_def)
--> 334                 raise ValueError(msg)
    335             spec_dict[self.__group_spec_cls.inc_key()] = parent_spec
    336         it = chain(spec_dict.get('groups', list()), spec_dict.get('datasets', list()))

ValueError: Cannot resolve include spec 'NWBDataInterface' for type 'CorticalSurface'
```

### PR DESCRIPTION
**Pull request by ajtritt**
## Motivation

Fix #541 

## How to test the behavior?
```
io = NWBHDF5IO('cache_spec_example.nwb', mode='r', load_namespaces=True)
```

See docs/gallery/general/extensions.py

## Checklist

- [ ] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [ ] Have you ensured the PR description clearly describes problem and the solution?
- [ ] Is your contribution compliant with our coding style ? This can be checked running `flake8` from the source directory.
- [ ] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [ ] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ?

### CODE REVIEW

**Comment by bendichter** [comment]
Looks great! Does the demo double as a test? Maybe we could throw in a few unit tests and see if we can appease the code coverage bot.

**Review by oruebel — DISMISSED** [review]

**Comment by ajtritt** [comment]
I use the demos as tests. But it doesn't count as a *unit* test, so it doesn't get counted by code coverage. I'll add something more unittesty to appease the CI deities.

**Comment by bendichter** [comment]
I don't think this is really working for me. If I use:

```python
from pynwb import NWBHDF5IO, NWBFile
from general import CatCellInfo
nwbfile = NWBFile("source", "a file with header data", "NB123A", '2018-06-01T00:00:00')
module = nwbfile.create_processing_module('a','b','c')
module.add_container(CatCellInfo('a','b','c', indices=[0,1,2]))
with NWBHDF5IO('test.nwb','w') as io:
    io.write(nwbfile, cache_spec=True)
```

and then in a new session I use:
```python
from pynwb import NWBHDF5IO
with NWBHDF5IO('test.nwb', 'r', load_namespaces=True) as io:
    nwbfile = io.read()
```

I get an error (no error if they are run in the same session). The error is:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/dev/pynwb/src/pynwb/form/build/map.py in construct(self, **kwargs)
    834         try:
--> 835             obj = cls(**kwargs)
    836             obj.container_source = builder.source

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
--> 329                     raise_from(TypeError(msg), None)
    330                 return func(self, **parsed['args'])

~/anaconda3/lib/python3.6/site-packages/six.py in raise_from(value, from_value)

TypeError: missing argument 'help', incorrect type for 'values' (got 'ndarray', expected 'str')

The above exception was the direct cause of the following exception:

Exception                                 Traceback (most recent call last)
<ipython-input-1-18ecf886d686> in <module>()
      1 from pynwb import NWBHDF5IO
      2 with NWBHDF5IO('test.nwb', 'r', load_namespaces=True) as io:
----> 3     nwbfile = io.read()

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/backends/io.py in read(self, **kwargs)
     31     def read(self, **kwargs):
     32         f_builder = self.read_builder()
---> 33         container = self.__manager.construct(f_builder)
     34         return container
     35 

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/build/map.py in construct(self, **kwargs)
    175         result = self.__containers.get(builder_id)
    176         if result is None:
--> 177             result = self.__type_map.construct(builder, self)
    178             parent_builder = self.__get_parent_dt_builder(builder)
    179             if parent_builder is not None:

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/build/map.py in construct(self, **kwargs)
   1236                              % str(container.__class__.__name__))  # noqa: F821
   1237         else:
-> 1238             return attr_map.construct(builder, build_manager)
   1239 
   1240     @docval({"name": "container", "type": Container, "doc": "the container to convert to a Builder"},

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/build/map.py in construct(self, **kwargs)
    813         cls = manager.get_cls(builder)
    814         # gather all subspecs
--> 815         subspecs = self.__get_subspec_values(builder, self.spec, manager)
    816         # get the constructor argument each specification corresponds to
    817         const_args = dict()

~/dev/pynwb/src/pynwb/form/build/map.py in __get_subspec_values(self, builder, spec, manager)
    799                             ret[subspec] = val
    800                     else:
--> 801                         result = self.__get_subspec_values(sub_builder, subspec, manager)
    802                         ret.update(result)
    803         else:

~/dev/pynwb/src/pynwb/form/build/map.py in __get_subspec_values(self, builder, spec, manager)
    790                     if self.__data_type_key in sub_builder.attributes or \
    791                        not (subspec.data_type_inc is None and subspec.data_type_def is None):
--> 792                         val = manager.construct(sub_builder)
    793                         if subspec.is_many():
    794                             if subspec in ret:

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/build/map.py in construct(self, **kwargs)
    175         result = self.__containers.get(builder_id)
    176         if result is None:
--> 177             result = self.__type_map.construct(builder, self)
    178             parent_builder = self.__get_parent_dt_builder(builder)
    179             if parent_builder is not None:

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/build/map.py in construct(self, **kwargs)
   1236                              % str(container.__class__.__name__))  # noqa: F821
   1237         else:
-> 1238             return attr_map.construct(builder, build_manager)
   1239 
   1240     @docval({"name": "container", "type": Container, "doc": "the container to convert to a Builder"},

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/build/map.py in construct(self, **kwargs)
    813         cls = manager.get_cls(builder)
    814         # gather all subspecs
--> 815         subspecs = self.__get_subspec_values(builder, self.spec, manager)
    816         # get the constructor argument each specification corresponds to
    817         const_args = dict()

~/dev/pynwb/src/pynwb/form/build/map.py in __get_subspec_values(self, builder, spec, manager)
    790                     if self.__data_type_key in sub_builder.attributes or \
    791                        not (subspec.data_type_inc is None and subspec.data_type_def is None):
--> 792                         val = manager.construct(sub_builder)
    793                         if subspec.is_many():
    794                             if subspec in ret:

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/build/map.py in construct(self, **kwargs)
    175         result = self.__containers.get(builder_id)
    176         if result is None:
--> 177             result = self.__type_map.construct(builder, self)
    178             parent_builder = self.__get_parent_dt_builder(builder)
    179             if parent_builder is not None:

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/build/map.py in construct(self, **kwargs)
   1236                              % str(container.__class__.__name__))  # noqa: F821
   1237         else:
-> 1238             return attr_map.construct(builder, build_manager)
   1239 
   1240     @docval({"name": "container", "type": Container, "doc": "the container to convert to a Builder"},

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/build/map.py in construct(self, **kwargs)
    837         except Exception as ex:
    838             msg = 'Could not construct %s object' % (cls.__name__,)
--> 839             raise_from(Exception(msg), ex)
    840         return obj
    841 

~/anaconda3/lib/python3.6/site-packages/six.py in raise_from(value, from_value)

Exception: Could not construct CatCellInfo object
```

Here's my `general.py`:
```python
from collections import Iterable

from pynwb import load_namespaces, register_class
from pynwb.core import NWBDataInterface
from pynwb.form.utils import docval, popargs

# load custom classes
name = 'general'
ns_path = name + '.namespace.yaml'
ext_source = name + '.extensions.yaml'
load_namespaces(ns_path)


@register_class('CatCellInfo', name)
class CatCellInfo(NWBDataInterface):
    __nwbfields__ = ('values', 'indices', 'cell_index')

    @docval({'name': 'name', 'type': str, 'doc': 'name'},
            {'name': 'source', 'type': str, 'doc': 'source?'},
            {'name': 'values', 'type': Iterable, 'doc': 'unique values as strings'},
            {'name': 'indices', 'type': Iterable, 'doc': 'indexes into those values'},
            {'name': 'cell_index', 'type': Iterable,  'default': None,
             'doc': 'global id for neuron'})
    def __init__(self, **kwargs):
        name, source, values, indices, cell_index = popargs(
            'name', 'source', 'values', 'indices', 'cell_index', kwargs)
        super(CatCellInfo, self).__init__(source, name, **kwargs)

        self.values = values
        self.indices = indices
        if cell_index is not None:
            self.cell_index = cell_index
```

and here's my `general.namespace.yaml`:
```
namespaces:
- doc: general extensions
  name: general
  schema:
  - namespace: core
  - source: general.extensions.yaml
```

and my `general.extensions.yaml`:
```
groups:
- datasets:
  - doc: global id for neuron
    dtype: int
    name: cell_index
    quantity: '?'
    shape:
    - null
    - 1
  - attributes:
    - doc: values that the indices are indexing
      dtype: text
      name: values
      shape:
      - null
      - 1
    doc: list of indices for values
    dtype: int
    name: indices
    shape:
    - null
    - 1
  doc: Categorical Cell Info
  neurodata_type_def: CatCellInfo
  neurodata_type_inc: NWBDataInterface
```

I _think_ that's all the info you need to re-create

**Comment by ajtritt** [comment]
@bendichter That's because it's using an autogenerated class for the read portion when you run it separately. Try importing the `general` module in the new session for reading.

**Comment by bendichter** [comment]
@ajtritt I'd need to call `load_namespaces(yaml_file)` in order to register the
class, which means I need to have the namespaces yaml file external to the
NWB file. What is the point of caching the spec if reading the file will
always require external yaml files anyway?

**Comment by bendichter** [comment]
also, there's an error if `load_namespaces=True` but no extensions were saved:
```python
from pynwb import NWBFile, NWBHDF5IO
nwbfile = NWBFile("source", "a file with header data", "NB123A", '2018-06-01T00:00:00')
with NWBHDF5IO('test.nwb', 'w') as io:
    io.write(nwbfile)
with NWBHDF5IO('test.nwb', 'r', load_namespaces=True) as io:
    io.read()
```

error:
```python
Traceback (most recent call last):
id in constructor = 4488584608
  File "/Users/bendichter/dev/to_nwb/test2.py", line 9, in <module>
    with NWBHDF5IO('test.nwb', 'r', load_namespaces=True) as io:
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/__init__.py", line 210, in __init__
    super(NWBHDF5IO, self).load_namespaces(ns_catalog, path)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py", line 70, in load_namespaces
    spec_group = f[f.attrs[SPEC_LOC_ATTR]]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/bendichter/anaconda3/envs/dev_pynwb/lib/python3.6/site-packages/h5py/_hl/attrs.py", line 60, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 77, in h5py.h5a.open
KeyError: "Can't open attribute (can't locate attribute: '.specloc')"
```

**Comment by bendichter** [comment]
EDIT: I fixed this

@ajtritt 
There's an error when you save an NWB file with a cached spec in python3 and load it in python2:

save (in python3):
```python
from pynwb import NWBHDF5IO, NWBFile, TimeSeries
from general import CatCellInfo
nwbfile = NWBFile("source", "a file with header data", "NB123A", '2018-06-01T00:00:00')
nwbfile.add_acquisition(TimeSeries(rate=1., data=[1,2,3], name='aa', source='source', unit='v'))
module = nwbfile.create_processing_module('a','b','c')
module.add_container(CatCellInfo('z','z','z', indices=[0,1,2]))
with NWBHDF5IO('test2.nwb','w') as io:
    io.write(nwbfile, cache_spec=True)
```

load (in python2):
```python
from pynwb import NWBHDF5IO
with NWBHDF5IO('test2.nwb', 'r', load_namespaces=True) as io:
    nwbfile = io.read()
```

traceback:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-83dc7808c82b> in <module>()
      1 from pynwb import NWBHDF5IO
      2 with NWBHDF5IO('/Users/bendichter/Desktop/Buzsaki/SenzaiBuzsaki2017/code/test2.nwb', 'r', load_namespaces=True) as io:
----> 3     nwbfile = io.read()

/Users/bendichter/dev/pynwb/src/pynwb/form/utils.pyc in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

/Users/bendichter/dev/pynwb/src/pynwb/form/backends/io.pyc in read(self, **kwargs)
     31     def read(self, **kwargs):
     32         f_builder = self.read_builder()
---> 33         container = self.__manager.construct(f_builder)
     34         return container
     35 

/Users/bendichter/dev/pynwb/src/pynwb/form/utils.pyc in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py in construct(self, **kwargs)
    172         result = self.__containers.get(builder_id)
    173         if result is None:
--> 174             result = self.__type_map.construct(builder, self)
    175             parent_builder = self.__get_parent_dt_builder(builder)
    176             if parent_builder is not None:

/Users/bendichter/dev/pynwb/src/pynwb/form/utils.pyc in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py in construct(self, **kwargs)
   1241                              % str(container.__class__.__name__))  # noqa: F821
   1242         else:
-> 1243             return attr_map.construct(builder, build_manager)
   1244 
   1245     @docval({"name": "container", "type": Container, "doc": "the container to convert to a Builder"},

/Users/bendichter/dev/pynwb/src/pynwb/form/utils.pyc in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py in construct(self, **kwargs)
    810         cls = manager.get_cls(builder)
    811         # gather all subspecs
--> 812         subspecs = self.__get_subspec_values(builder, self.spec, manager)
    813         # get the constructor argument each specification corresponds to
    814         const_args = dict()

/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py in __get_subspec_values(self, builder, spec, manager)
    796                             ret[subspec] = val
    797                     else:
--> 798                         result = self.__get_subspec_values(sub_builder, subspec, manager)
    799                         ret.update(result)
    800         else:

/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py in __get_subspec_values(self, builder, spec, manager)
    787                     if self.__data_type_key in sub_builder.attributes or \
    788                        not (subspec.data_type_inc is None and subspec.data_type_def is None):
--> 789                         val = manager.construct(sub_builder)
    790                         if subspec.is_many():
    791                             if subspec in ret:

/Users/bendichter/dev/pynwb/src/pynwb/form/utils.pyc in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py in construct(self, **kwargs)
    172         result = self.__containers.get(builder_id)
    173         if result is None:
--> 174             result = self.__type_map.construct(builder, self)
    175             parent_builder = self.__get_parent_dt_builder(builder)
    176             if parent_builder is not None:

/Users/bendichter/dev/pynwb/src/pynwb/form/utils.pyc in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py in construct(self, **kwargs)
   1241                              % str(container.__class__.__name__))  # noqa: F821
   1242         else:
-> 1243             return attr_map.construct(builder, build_manager)
   1244 
   1245     @docval({"name": "container", "type": Container, "doc": "the container to convert to a Builder"},

/Users/bendichter/dev/pynwb/src/pynwb/form/utils.pyc in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py in construct(self, **kwargs)
    810         cls = manager.get_cls(builder)
    811         # gather all subspecs
--> 812         subspecs = self.__get_subspec_values(builder, self.spec, manager)
    813         # get the constructor argument each specification corresponds to
    814         const_args = dict()

/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py in __get_subspec_values(self, builder, spec, manager)
    787                     if self.__data_type_key in sub_builder.attributes or \
    788                        not (subspec.data_type_inc is None and subspec.data_type_def is None):
--> 789                         val = manager.construct(sub_builder)
    790                         if subspec.is_many():
    791                             if subspec in ret:

/Users/bendichter/dev/pynwb/src/pynwb/form/utils.pyc in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py in construct(self, **kwargs)
    172         result = self.__containers.get(builder_id)
    173         if result is None:
--> 174             result = self.__type_map.construct(builder, self)
    175             parent_builder = self.__get_parent_dt_builder(builder)
    176             if parent_builder is not None:

/Users/bendichter/dev/pynwb/src/pynwb/form/utils.pyc in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py in construct(self, **kwargs)
   1236         if build_manager is None:
   1237             build_manager = BuildManager(self)
-> 1238         attr_map = self.get_map(builder)
   1239         if attr_map is None:
   1240             raise ValueError('No ObjectMapper found for builder of type %s'

/Users/bendichter/dev/pynwb/src/pynwb/form/utils.pyc in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py in get_map(self, **kwargs)
   1167             data_type = self.get_builder_dt(obj)
   1168             namespace = self.get_builder_ns(obj)
-> 1169             container_cls = self.get_cls(obj)
   1170         # now build the ObjectMapper class
   1171         spec = self.__ns_catalog.get_spec(namespace, data_type)

/Users/bendichter/dev/pynwb/src/pynwb/form/utils.pyc in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py in get_cls(self, **kwargs)
   1102         data_type = self.get_builder_dt(builder)
   1103         namespace = self.get_builder_ns(builder)
-> 1104         return self.get_container_cls(namespace, data_type)
   1105 
   1106     @docval({'name': 'spec', 'type': (DatasetSpec, GroupSpec), 'doc': 'the parent spec to search'},

/Users/bendichter/dev/pynwb/src/pynwb/form/utils.pyc in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py in get_container_cls(self, **kwargs)
   1057                     fields[k] = field_spec
   1058             d = {'__init__': self.__get_constructor(parent_cls, fields)}
-> 1059             cls = type(name, bases, d)
   1060             self.register_container_type(namespace, data_type, cls)
   1061         return cls

TypeError: type() argument 1 must be string, not unicode
```

**Pull request merged**
