### PR TITLE
Better testing

### PR DESCRIPTION
**Pull request by t-b**
Test the code in `docs/code` as well.

### CODE REVIEW

**Review by rly — APPROVED** [review]

**Comment by rly** [comment]
@t-b where is `docs/code/creating-and-writing-nwbfile.py` referenced? I did a search for the filename and could not find anything. Is it legacy code that can be removed?

**Comment by t-b** [comment]
I thought it was used in sphinx, but turns out that was old knowledge. It is not use anymore since 8a32eb77 (mv examples to extensions, 2018-03-29).

**Comment by rly** [comment]
Thanks for digging that up. I vote to remove that script, since it is redundant with the examples in `docs/gallery/`. It would be one less thing to maintain. And then we would not need this PR.

**Comment by rly** [comment]
I removed the script and directory in https://github.com/NeurodataWithoutBorders/pynwb/pull/1055/commits/69679264abfbd6396cae0b9b95d344b808a40c6d in PR #1055, so this PR is no longer necessary. Thanks for pointing out the dead code, @t-b !

**Pull request closed without merging**
